- core/src/main/java/com/yahoo/ycsb/TerminatorThread.java
- mongodb/src/main/java/com/yahoo/ycsb/db/MongoDbClient.java
- pom.xml
Looks like MapKeeper has been failing for some time due the jar not being available. Lets remove the dependency for now so commits can run the build.
> Remove mapkeeper so that build passes

- bin/ycsb
- hbase/pom.xml
- hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java
- pom.xml
HBase 1.0 [introduced a new
API](https://blogs.apache.org/hbase/entry/start_of_a_new_era); this pull
request adds support for it:
* Bumps `hbase.version` to 1.0.0.
* Adds a new database, `hbase-10`, which targets the HBase 1.0 API.
The `hbase-10` database also supports configurable use of client-side buffering (see #98).
> Add an HBase 1.0 client.

- core/src/main/java/com/yahoo/ycsb/measurements/Measurements.java
Previously the method `Measurements.getSummary()` wasn't set to synchronized, which was occasionally resulting in `java.util.ConcurrentModificationException` being raised when running YCSB with multiple threads. This commit fixes the issue by simply adding the `synchronized` keyword to `Measurements.getSummary()`.
Let me know if you can think of any potential issues with making this change. I'm unsure if `getSummary()` was deliberately left unsynchronized for a reason?
> Synchronize Measurements.getSummary() method to prevent ConcurrentModificationExceptions

- hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient.java
Reasons are detailed in https://issues.apache.org/jira/browse/HBASE-9521
This makes errors simpler to understand: without this setting, the failed insertions are retried when we close the connection to HBase.
> Use the clear buffer on fail option. Not using it is now deprecated.

- hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient.java
- hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java
Hbase client has a bug to write all values as empty byte arrays in debug mode. It is caused by an illegal use of ByteIterator. Values returned from toString() or toArray() should be cached if they are needed later.
> Fix hbase client's write bug in debug mode.

- core/src/main/java/com/yahoo/ycsb/Client.java
- core/src/main/java/com/yahoo/ycsb/CommandLine.java
- core/src/main/java/com/yahoo/ycsb/measurements/Measurements.java
Previously the YCSB core code contained some hard-coded property keys, with others defined as constants. This pull request removes the remaining hard-coded strings in favour of string constants defined in `core/src/main/java/com/yahoo/ycsb/Client.java` and `core/src/main/java/com/yahoo/ycsb/measurements/Measurements.java`.
> Remove hard-coded property key strings in favour of string constants

- hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient.java
- hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java
Add `autoflush` property to HBaseClient. It enables to turn on or off auto flush flag of HTable.
> Add autoflush property to HBaseClient

- bin/ycsb
- mongodb/README.md
- mongodb/pom.xml
- mongodb/src/main/java/com/yahoo/ycsb/db/AsyncMongoDbClient.java
- mongodb/src/main/java/com/yahoo/ycsb/db/MongoDbClient.java
- mongodb/src/main/java/com/yahoo/ycsb/db/OptionsSupport.java
- mongodb/src/test/java/com/yahoo/ycsb/db/OptionsSupportTest.java
- pom.xml
This pull request contains a new driver for MongoDB based on the [asynchronous driver](http://github.com/allanbank/mongodb-async-driver). The bulk of the changes are adding the required logic to the startup scripts to support the second driver. I have used this branch to run a series of [benchmarks](http://www.allanbank.com/mongodb-async-driver/performance/ycsb.html).
There are also a number of community contributed updates to the old MongoDB Driver. These include:
* Updated README with specific instructions for running a MongoDB suite.
* Updates to the configuration to now be strictly based on a [MongoDB Connection String URI](http://docs.mongodb.org/manual/reference/connection-string/) which is standardized across drivers.
* Other small fixes and performance enhancements.
This pull …
> Async mongodb driver

- accumulo/pom.xml
- cassandra/pom.xml
- core/pom.xml
- distribution/pom.xml
- dynamodb/pom.xml
- elasticsearch/pom.xml
- gemfire/pom.xml
- hbase/pom.xml
- hypertable/pom.xml
- infinispan/pom.xml
- jdbc/pom.xml
- mapkeeper/pom.xml
- mongodb/pom.xml
- nosqldb/pom.xml
- orientdb/pom.xml
- pom.xml
- redis/pom.xml
- voldemort/pom.xml
* Need a SNAPSHOT version because non-SNAPSHOT is reserved for actual releases.
* Increment minor version per pre-1.0 guidelines from the Version Numbers guide
Fixes #236.
> [version] update to 0.2.0-SNAPSHOT.

- core/src/main/java/com/yahoo/ycsb/workloads/CoreWorkload.java
Added additional parameter to turn on deterministic creation of values for
specified keys. When running a workload, read data is checked against the
deterministic value and inconsistencies exported to the measurements object.
Discovered flaws in multithreaded YCSB 'latest' workload distribution as
data may be read by one thread before it is written by another.
Part of previous pull request 87:
https://github.com/brianfrankcooper/YCSB/pull/87
> Data Correctness Checking

- hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient.java
- hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java
Make write buffer size of HBase client configurable by adding a new property `writebuffersize`.
> Make write buffer size of HBase client configurable

- bin/ycsb
* Use argparse for argument parsing.
* Add a '--jvm-args' flag, to pass arbirary options to java.
* Add a '-cp' flag, which allows prepending paths to the java classpath.
* Exit with the return code from java.
Requires Python 2.7.
> Clean up bin/ycsb.

- gemfire/pom.xml
- pom.xml
* rebased the changes from #94 to current master, squashed them into one commit.
* looking at the references S3 based repo, the most recent version of the artifact the original binding is based on is 8.1.0.
I'd really like to update to a more recent gemfire binding, and one that isn't coming from an s3 bucket. I'll file a follow-on once this goes in. if we can find someone to do the work maybe spring-data-gemfire is the way to go?
> Rebase and updated PR-94: "bump gemfire version to 7.0.2"

- core/src/main/java/com/yahoo/ycsb/measurements/exporter/JSONArrayMeasurementsExporter.java
- core/src/test/java/com/yahoo/ycsb/measurements/exporter/TestMeasurementsExporter.java
Had some problems with my branch for #287. In this branch i fixed the depricated message for DefaultPrettyPrinter by importing `org.codehaus.jackson.util.DefaultPrettyPrinter` and added the JSONArrayMeasurementsExporter, which generates one JSON array with many measurement objects.
>  [exporter] added JSONArrayMeasurementsExporter

- binding-parent/datastore-specific-descriptor/src/main/resources/assemblies/datastore-specific-assembly.xml
found an error in our packaging while reviewing #302 that keeps all of our datastore binding specific distribution artifacts from working.
this should block starting the release branch for #266, since we know it breaks so much.
> [packaging] ensure datastore binding specific distributions include core transitive deps

- mongodb/README.md
- mongodb/src/main/java/com/yahoo/ycsb/db/AsyncMongoDbClient.java
- mongodb/src/main/java/com/yahoo/ycsb/db/MongoDbClient.java
[mongodb] update parameter for connection url to match previous behavior and docs.
Changes:
1. mongodb configuration parameter bug (mongodb.url)
Even though the documentation mentioned mongodb.url, the code was expecting mongodatabase.url property. Modified the code and comments in code to point to correct link.
2. README file change
Default DB is 'ycsb'
3. Some cleanup.
> [mongodb] update parameter for connection url to match previous behavior and docs.

- hbase/README.md
Note pre-splitting, document 'columnfamily' parameter.
Fixes #321
> HBase README updates

- bin/ycsb
closes #315 
In addition to not being able to run from source, the current classpath determination
* can't handle any case where the binding directory has a name different from the database specified (i.e. hbase-10, cassanda-cql, etc in the general purpose artifact)
* doesn't add the 'conf' dir for binding-specific artifacts to the classpath
Tested by running shell with tarantool, hbase, and accumulo from source and examining classpath, then doing the same from the general artifact, then doing the same from the tarantool and hbase specific artifacts.
> [scripts] clean up runtime classpath.

- core/src/main/java/com/yahoo/ycsb/Client.java
As it is right now, the number of executed operations is rounded down to the nearest multiple of the thread count.
This is a little confusing, if you, say, insert 3,000,000 records into a database using 7 threads and the database then contains only 2,999,997 records after that.
> Execute correct number of operations

- cassandra/src/main/java/com/yahoo/ycsb/db/CassandraClient10.java
Because different clusters may use different ports, get the value of the port from property file is better than a constant value. Just as what CassandraCQLClient does.
> [Cassandra] change the port of Cassandra (previous version 1.2) as a parameter instead of a constant value such as 9160

- core/src/main/java/com/yahoo/ycsb/Client.java
- core/src/main/java/com/yahoo/ycsb/TerminatorThread.java
There are two commits. 
The first has the actual fix which uses a CountDownLatch to notify the StatusThread when all of the clients have completed. 
The second removes whitespace at the ends of lines and replaces tabs with 4 spaces.
> Shutdown the status thread as soon as clients complete (Issue #316)

- core/src/main/java/com/yahoo/ycsb/measurements/OneMeasurementHdrHistogram.java
The HdrHistogramReader makes some problematic assumptions on the roles played by start time, base time and histogram start/end times. This is to be revisited in a future release of HdrHistogram (see HdrHistogram/HdrHistogram#69). In the meantime this change will make YCSB record as expected by the current reader:
a. Set histogram log base time (same as start time)
b. Only create the recorder after the log has been setup
> [core] Fix #380 by working around recorder/logger initialization timing.

- core/src/main/java/com/yahoo/ycsb/measurements/Measurements.java
- core/src/main/java/com/yahoo/ycsb/measurements/OneMeasurement.java
- core/src/main/java/com/yahoo/ycsb/measurements/OneMeasurementHdrHistogram.java
- core/src/main/java/com/yahoo/ycsb/measurements/OneMeasurementHistogram.java
- core/src/main/java/com/yahoo/ycsb/measurements/OneMeasurementTimeSeries.java
- core/src/test/java/com/yahoo/ycsb/measurements/exporter/TestMeasurementsExporter.java
This is first step to removing internal implementation which is made obsolete by HdrHistogram
> [core] Make hdrhistogram default measurement type

- core/src/main/java/com/yahoo/ycsb/generator/AcknowledgedCounterGenerator.java
- core/src/main/java/com/yahoo/ycsb/workloads/CoreWorkload.java
I had been having issues with workload D, where a lot of reads try to access records that don't exist. The reason was how insert transactions worked:
1) Generate a new key for the record to be inserted with transactioninsertkeysequence.nextInt().
2) Write the record to the database using the new key.
However, between 1) and 2), nextKeynum() already considered the new key to be valid, i.e., reads of workload D tried to use that key. Even though the record was not yet in the database.
The proposed fix makes using transactioninsertkeysequence a 2-step process:
1) Invoke transactioninsertkeysequence.nextInt() to get a new key, x.
2) Write the new record to the database.
3) Invoke transactioninsertkeysequence.acknowledge(x) to acknowledge the new key, i.e., signal that it is now available in …
> Proposed fix for #327.

- aerospike/src/main/java/com/yahoo/ycsb/db/AerospikeClient.java
As per @cmccoy's comment in #324: Database adapters shouldn't introduce any new functionality. They should just pass things back and forth between YCSB and the database client.
This change removes back-off/retry logic for cluster overload conditions from the Aerospike adapter.
> Bring Aerospike adapter in line with adapter policy

- hbase098/README.md
- hbase098/src/main/java/com/yahoo/ycsb/db/HBaseClient.java
- hbase10/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java
Other bindings limit the number of results retrieved from the server. The HBase bindings just close the scanner once they have received the desired number of records. Adding a [PageFilter](https://hbase.apache.org/apidocs/org/apache/hadoop/hbase/filter/PageFilter.html) matches the behavior of other bindings, and should improve performance.
> Use a PageFilter in HBase scans

- cassandra/src/main/java/com/yahoo/ycsb/db/CassandraCQLClient.java
* Changes the default port to 9042 (this is the default CQL port, the current
default is the Thrift API port).
* Changes property `host` from a space-separated list to property
`hosts`, a comma-separated list (to match the Thrift clients).
* Updates a few messages.
> [cassandra-cql] Make CassandraCQLClient consistent.

- redis/README.md
`redis.host`, is correct, rather than `redis.url`.
> [redis] Fix the label for a redis parameter

- mongodb/README.md
- mongodb/src/main/java/com/yahoo/ycsb/db/AsyncMongoDbClient.java
- mongodb/src/main/java/com/yahoo/ycsb/db/MongoDbClient.java
- mongodb/src/test/java/com/yahoo/ycsb/db/AbstractDBTestCases.java
- mongodb/src/test/java/com/yahoo/ycsb/db/AsyncMongoDbClientTest.java
- mongodb/src/test/java/com/yahoo/ycsb/db/MongoDbClientTest.java
Added a configuration option (mongodb.upsert) to control if the driver
performs inserts or upserts operations for the DB.insert() method.
Defaults to doing inserts.
Note: Change in behavior from previous versions that performed upserts
for non-batched DB.insert() operations.
Fixes #400.
> [mongodb] Add mongodb.upsert configuration option.

- core/src/main/java/com/yahoo/ycsb/generator/AcknowledgedCounterGenerator.java
- core/src/test/java/com/yahoo/ycsb/generator/AcknowledgedCounterGeneratorTest.java
Update the AcknowledgedCounterGenerator to use a power of two size for the window so a mask can be used instead of a modulo operation. This avoid issues when there is overflow of the id integer values to negative values.
> [core] Update the AcknowledgedCounterGenerator to use a power of two and mask.

- hbase10/src/test/java/com/yahoo/ycsb/db/HBaseClient10Test.java
I believe this should fix #434.
> [hbase10] Skip HBase MiniCluster tests on Windows

- bin/ycsb
To accomplish this, just need to alter the classpath logic when given 'basic' as the DB. It looked like you just needed a built core jar to run the BasicDB from source.
get_classpath_from_maven(database) now puts the database directly into maven command as opposed to appending '-bending'. This allowed all logic to happen in main().
In main() now using the 'core' dir and the 'core' project if using the 'basic' database. Otherwise things happen as normal.
> Fixed #336. Classpath handling BasicDB from source

- bin/ycsb
- distribution/pom.xml
- kudu/README.md
- kudu/pom.xml
- kudu/src/main/conf/log4j.properties
- kudu/src/main/java/com/yahoo/ycsb/db/KuduYCSBClient.java
- pom.xml
Currently doesn't include unit tests since we don't have mock objects for that.
> Add Kudu bindings

- bin/ycsb
- cassandra/README.md
- cassandra/src/main/java/com/yahoo/ycsb/db/CassandraCQLClient.java
- cassandra2/README.md
- cassandra2/pom.xml
- cassandra2/src/main/java/com/yahoo/ycsb/db/CassandraCQLClient.java
- cassandra2/src/test/java/com/yahoo/ycsb/db/CassandraCQLClientTest.java
- cassandra2/src/test/resources/ycsb.cql
- pom.xml
I couldn't find a way to make the Cassandra CQL driver work with both versions <2.0 and >2.1, so I added a separate binding, which is almost identical to the `CassandraCQLBinding` in `cassandra/`.
Also adds integration tests for the new binding, and some brief READMEs.
Addresses #421 and #293, possibly #369.
> Adds a Cassandra 2 CQL binding.

- binding-parent/pom.xml
- distribution/pom.xml
Without this people who have a large gid will error out with:
group id '1519764623' is too big ( > 2097151 )
> Add posix compatibility to distribution.

- jdbc/src/main/java/com/yahoo/ycsb/db/JdbcDBClient.java
Now properly enforcing a scan of the given number of documents in the
scan operation using the LIMIT modifier in the cached statement.
Fixes #171.
> [jdbc] added LIMIT to JDBC scan operation

- jdbc/src/main/java/com/yahoo/ycsb/db/JdbcDBClient.java
This was going to get fixed with #447 but not sure that is a valid PR anymore.
This fixes #128.
> [jdbc] removed semicolons from cached statements

- core/src/main/java/com/yahoo/ycsb/workloads/CoreWorkload.java
Changed measurement latency to actual latency time of the verifyRow step and now recording Status codes for verify operations.
Fixes #479
> [core] added return codes to VERIFY

- core/src/main/java/com/yahoo/ycsb/workloads/CoreWorkload.java
When dataintegrity and readallfields are both true, pass the full field
set to db.read() so that the field values can be verified.
Fixes #496
> [core] passing full fieldset for verification

- bin/ycsb
- distribution/pom.xml
- googledatastore/README.md
- googledatastore/conf/googledatastore.properties
- googledatastore/pom.xml
- googledatastore/src/main/java/com/yahoo/ycsb/db/GoogleDatastoreClient.java
- googledatastore/src/main/java/com/yahoo/ycsb/db/package-info.java
- googledatastore/src/main/resources/log4j.properties
- pom.xml
Add a DB client for [Google Cloud Datastore](https://cloud.google.com/datastore/docs/concepts/overview?hl=en)
This Pull Request includes implementation of all CRUD operations (except scan), and integration into the rest of YCSB (pom.xml changes, etc).
> [googledatastore] Add a Google Datastore client

- .gitignore
This change ignores temporary files created by Vim and Emacs.
> Added support for Vim and Emacs in .gitignore

- core/src/main/java/com/yahoo/ycsb/DBWrapper.java
- workloads/workload_template
Plus some minor styling fixes: break long lines, replace tabs with white spaces.
> [core] Record latency of successful and failed operations separately

- .editorconfig
More info at http://editorconfig.org - this makes it easy for editors to
automatically perform the right indentation.
> Added editorconfig for easy style conformance.

- checkstyle.xml
Discussion for this change is in #267. Abridged - 80 character limit is too short to be practical.
This should not invalidate any checkstyle enforcement PRs already merged since we are making the limit larger. I can assist in reevaluating the modules that have already had their checkstyle enforcement merged.
@allanbank - I can help with the open checkstyle PRs as well, just let me know.
> [build] changed checkstyle linelength to 120

- bin/ycsb
* Handles missing "java" with an error message.
* Adds a check_output method for users running on Python 2.6.
* Prints an error when importing argparse fails (third party module on Python 2.6).
Partially addresses #341, fixes #345.
> [scripts] Improve errors in bin/ycsb

- kudu/src/main/java/com/yahoo/ycsb/db/KuduYCSBClient.java
- pom.xml
This version and the previous one are wire compatible, the only code
chance reflects a naming change in the client API.
> [kudu] Bump Kudu dependency to 0.6.0

- NOTICE.txt
- bin/ycsb
- distribution/pom.xml
- memcached/README.md
- memcached/conf/memcached.properties
- memcached/pom.xml
- memcached/src/main/java/com/yahoo/ycsb/db/MemcachedClient.java
- memcached/src/main/java/com/yahoo/ycsb/db/package-info.java
- pom.xml
The memcached support was extracted from PR #98 by @jbellis, with cleanups to
bring it in line with current APIs and style guide.
This PR also addresses issue #326.
@busbey, could you please review? Thanks!
> [memcached] Added memcached binding.

- core/src/main/java/com/yahoo/ycsb/workloads/CoreWorkload.java
- workloads/workload_template
The default behavior is NO RETRY, which is the current behavior.
But optionally user can enable retry if they are working with a DB backend that is better tolerated by allowing a few retries.
This is for issue #508 
Notes for reviewers: The first commit is purely formatting change only, the second commit is the change.
> [Core] Add retry for insertion logic to make the load process more robust

- memcached/pom.xml
For reference, other bindings don't appear to specify a `groupId` at this level
in their `pom.xml` files.
@shivam-maharshi says in a [comment][1]:
> The groupId here is the duplicate of the parent groupId. This is creating a
> problem in the maven build.
[1]: https://github.com/brianfrankcooper/YCSB/commit/d4b1d247a31cf9fbf42b2e324b5b1cc27fdd9565#commitcomment-15030853
> [memcached] Removed groupId (duplicates parent).

- cassandra2/README.md
- cassandra2/src/main/java/com/yahoo/ycsb/db/CassandraCQLClient.java
This PR actually fixes two issues, both related to property handling in the ```cassandra2-cql``` client.
1. In the spirit of keeping the clients as baseline as possible, I removed the magic number updates to read and connect timeouts to the cluster. Instead I exposed these properties to the user.
2. No longer setting the max connections to threadcount. As I discussed in #534, YCSB threads are not directly related with Cassandra Connections. I also exposed these settings to the user for fine tuning.
This PR would fix #534 and allows the ```cassandra2-cql``` client to be used on all Cassandra 2.X versions making the deprecation of the cassandra-binding in #532 a little easier.
> [cassandra2] added better property handling

- bin/ycsb
- cassandra/README.md
I chose 3 month deprecation period, sounds like no one is really using Cassandra 0.X or 1.X anymore. Also, this binding has caused some confusion on which to use for different versions of Cassandra (most Cassandra issues start with 'try using ```cassandra2-cql```), so best to remove it sooner rather than later.
Fixes #532
> [cassandra] added large deprecation message

- kudu/src/main/java/com/yahoo/ycsb/db/KuduYCSBClient.java
The default 10s timeout can be too low when creating large tables on
slow devices. This patch just uses the already-defined default of
60s for that operation.
> [kudu] Bump the default admin timeout

- mongodb/README.md
Updating the YCSB installation instruction. In some cases it is better to use the binary. (where mvn or the Internet connection is not available)
> [mongodb] Update the documentation for MongoDB. Use YCSB from binary instead

- mongodb/src/main/java/com/yahoo/ycsb/db/AsyncMongoDbClient.java
- mongodb/src/main/java/com/yahoo/ycsb/db/MongoDbClient.java
- mongodb/src/main/java/com/yahoo/ycsb/db/OptionsSupport.java
This ensures that users do not confuse the results from batched
and non-batched operations.
Closes #522
> [mongodb] Update to use BATCHED_OK Status for batched inserts.

- cassandra/src/main/java/com/yahoo/ycsb/db/CassandraCQLClient.java
- cassandra2/src/main/java/com/yahoo/ycsb/db/CassandraCQLClient.java
- dynamodb/src/main/java/com/yahoo/ycsb/db/DynamoDBClient.java
- hbase098/src/main/java/com/yahoo/ycsb/db/HBaseClient.java
- hbase10/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java
- jdbc/src/test/java/com/yahoo/ycsb/db/JdbcDBClientTest.java
- s3/src/main/java/com/yahoo/ycsb/db/S3Client.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1481 - Unused local variables should be removed
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1481
Kirill Vlasov
> Unused local variables should be removed

- core/src/main/java/com/yahoo/ycsb/StringByteIterator.java
- core/src/main/java/com/yahoo/ycsb/measurements/Measurements.java
- dynamodb/src/main/java/com/yahoo/ycsb/db/DynamoDBClient.java
- googledatastore/src/main/java/com/yahoo/ycsb/db/GoogleDatastoreClient.java
- infinispan/src/main/java/com/yahoo/ycsb/db/InfinispanRemoteClient.java
This pull request is focused on resolving occurrences of Sonar rules 
pmd:UnnecessaryConstructor - Unnecessary constructor, 
squid:EmptyStatementUsageCheck - Empty statements should be removed
https://dev.eclipse.org/sonar/coding_rules#q=pmd:UnnecessaryConstructor
https://dev.eclipse.org/sonar/coding_rules#q=squid:EmptyStatementUsageCheck
Kirill Vlasov
> pmd:UnnecessaryConstructor - Unnecessary constructor, squid:EmptyStatementUsageCheck - Empty statements should be removed

- accumulo/src/main/java/com/yahoo/ycsb/db/AccumuloClient.java
- accumulo/src/main/java/com/yahoo/ycsb/db/ZKProducerConsumer.java
- core/src/main/java/com/yahoo/ycsb/CommandLine.java
- couchbase/src/main/java/com/yahoo/ycsb/db/CouchbaseClient.java
- memcached/src/main/java/com/yahoo/ycsb/db/MemcachedClient.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1155 - Collection.isEmpty() should be used to test for emptiness
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1155
Kirill Vlasov
> Collection.isEmpty() should be used to test for emptiness

- cassandra2/src/main/java/com/yahoo/ycsb/db/CassandraCQLClient.java
Hi,
i removed the tracing from the insert statement cause it had a severe impact in performance.
Was there a reason for that or was i just left accidentally in the code?
Regards
Mike
> [Cassandra] removed tracing from insert

- s3/src/main/java/com/yahoo/ycsb/db/S3Client.java
This pull request is focused on resolving occurrences of Sonar rule squid:S1143 - "return" statements should not occur in "finally" blocks
https://dev.eclipse.org/sonar/coding_rules#q=squid:S1143
Kirill Vlasov
> "return" statements should not occur in "finally" blocks

- orientdb/README.md
- orientdb/src/main/java/com/yahoo/ycsb/db/OrientDBClient.java
This fixes the end table scanning brought up in #562.
While working on this I found some things that should probably be marked as known issues.
1. First is a performance issue, after testing with a few different recordcounts I found that iterateEntriesMajor() return time is directly linked with number of records in the table. So, a relatively small scan size will start to perform worse on larger tables. The better solution would have been to use iterateEntriesBetween(), problem is it takes a start and end key which is not how the current scan framework is set up. It may be a good idea to think about updating the scan operation to pass a recordcount as well as a corresponding endkey. This would benefit more bindings then OrientDB I believe. There are a few things that complicate that idea, …
> [orientdb] fixed end table scan issue

- cassandra/src/main/java/com/yahoo/ycsb/db/CassandraClient10.java
- cassandra/src/main/java/com/yahoo/ycsb/db/CassandraClient7.java
- cassandra/src/main/java/com/yahoo/ycsb/db/CassandraClient8.java
- core/src/main/java/com/yahoo/ycsb/BasicDB.java
- core/src/main/java/com/yahoo/ycsb/StringByteIterator.java
- gemfire/src/main/java/com/yahoo/ycsb/db/GemFireClient.java
- mapkeeper/src/main/java/com/yahoo/ycsb/db/MapKeeperClient.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2864 - "entrySet()" should be iterated when both the key and value are needed
https://dev.eclipse.org/sonar/coding_rules#q=squid:S2864
Kirill Vlasov
> "entrySet()" should be iterated when both the key and value are needed

- orientdb/pom.xml
- orientdb/src/test/java/com/yahoo/ycsb/db/OrientDBClientTest.java
Added basic operational test cases for the orientdb binding. Should give a little assurance to future cleanup work.
> [orientdb] added test cases

- accumulo/src/main/java/com/yahoo/ycsb/db/AccumuloClient.java
YCSB with Accumulo doesn't work in 0.5.0. 
The datastore binding caches a connection to the Accumulo client and handles set up only when the table being interacted with changes. The changes from #464 accidentally used the cached table name rather than the newly proposed table name.
On the first operation, the cached table name is blank which causes the Accumulo driver to error out.
> [accumulo] Accumulo binding does not work in 0.5.0 release

- elasticsearch/README.md
- elasticsearch/pom.xml
- elasticsearch/src/main/java/com/yahoo/ycsb/db/ElasticSearchClient.java
> [elasticsearch] Bump version from 0.19.8 to 2.1.1

- orientdb/pom.xml
- orientdb/src/main/java/com/yahoo/ycsb/db/OrientDBClient.java
- orientdb/src/test/java/com/yahoo/ycsb/db/OrientDBClientTest.java
- pom.xml
Bumping the version required a few support fixes to make things work:
1. There were some OrientDB API changes around the use of ```ORecordInternal```, not sure why that was being used in the first place, changed to ```ORecord```.
2. Made ```db``` reference protected so that it could be used by the test class. The way that Maven was running the tests (with multiple threads) was hitting a lot of issues with OrientDB thread safety. This was the easiest way around that.
3. The way the test class calls the clients ```cleanup()``` method required a oneliner to deal with the threads.
4. Part of the known issue about the broken iterator is that the iterator starts at index 1 instead of 0. I added a temporary fix in the test class so that the test could still pass.
> [orientdb] version bump to 2.1.8

- mongodb/src/main/resources/log4j.properties
Currently there is a lot of debug output from the mongodb module. By adding this log4j.properties file the DEBUG output is not displayed by default.
> Added log4j properties for mongodb to not show debug output as default

- bin/ycsb
- core/src/main/java/com/yahoo/ycsb/Status.java
- distribution/pom.xml
- pom.xml
- solr/README.md
- solr/pom.xml
- solr/src/main/java/com/yahoo/ycsb/db/SolrClient.java
- solr/src/main/java/com/yahoo/ycsb/db/package-info.java
Since ElasticSearch is supported I thought it would be beneficial to have Solr supported also. I'm sure there are people out there who would love to compare head-to-head these 2 search engine technologies.
> Adding Apache Solr Support

- solr/pom.xml
- solr/src/main/resources/log4j.properties
- solr/src/test/java/com/yahoo/ycsb/db/SolrClientBaseTest.java
- solr/src/test/java/com/yahoo/ycsb/db/SolrClientCloudTest.java
- solr/src/test/java/com/yahoo/ycsb/db/SolrClientTest.java
- solr/src/test/resources/solr_config/schema.xml
- solr/src/test/resources/solr_config/solrconfig.xml
Relies on PR #574. Relates to @busbey  comment about testing the Solr binding https://github.com/brianfrankcooper/YCSB/pull/574#issuecomment-170245724. Will most likely need to be rebased after #574 is merged.
> [solr] Added tests for Solr binding

- core/src/main/java/com/yahoo/ycsb/Client.java
- core/src/main/java/com/yahoo/ycsb/generator/IntegerGenerator.java
- core/src/main/java/com/yahoo/ycsb/generator/ScrambledZipfianGenerator.java
- core/src/main/java/com/yahoo/ycsb/workloads/ConstantOccupancyWorkload.java
This pull request is focused on resolving occurrences of Sonar rule squid:S2131 - Primitives should not be boxed just for "String" conversion
https://dev.eclipse.org/sonar/coding_rules#q=squid:S2131
Kirill Vlasov
> Primitives should not be boxed just for "String" conversion

- core/src/main/java/com/yahoo/ycsb/Client.java
- orientdb/README.md
- orientdb/pom.xml
- orientdb/src/main/java/com/yahoo/ycsb/db/OrientDBClient.java
Had to implement a separate init path for remote connections using OServerAdmin. The old, local init path is essentially the same as before.
OrientDB does not support the iterator methods that scan is built off of for remote connections, so had to check for that and record NOT_IMPLEMENTED. Made a note of that in the README as well.
> [orientdb] Added remote connection capabilties

- orientdb/pom.xml
- orientdb/src/main/java/com/yahoo/ycsb/db/OrientDBClient.java
- orientdb/src/main/java/com/yahoo/ycsb/db/package-info.java
- orientdb/src/test/java/com/yahoo/ycsb/db/OrientDBClientTest.java
* Rabased pull/489/head to master
* Backed out unnecessary line breaks for 120 char limit
* Enforced checkstyle on new code
* Was required to make db variable private, updated in tests
* Removed TODO
Closes #489
> Orientdb checkstyle

- orientdb/README.md
- orientdb/pom.xml
- orientdb/src/main/java/com/yahoo/ycsb/db/OrientDBClient.java
- orientdb/src/main/resources/log4j.properties
Two things fixed here:
* Added logging
* Moved Intent to a property, before it was always being called as massiveinsert which, is not always a good thing to do. It should be at the control of the user.
> Orientdb cleanup

- dynamodb/pom.xml
- dynamodb/src/main/java/com/yahoo/ycsb/db/DynamoDBClient.java
Run workloada from an external vm to dynamodb, the performance difference between  dynamodb v1 and v2 api. Results:
percentile,	v1 read,	v1 write,	v2 read,	v2 write
0.1,	34775.9,  	36097,	35244,	36357
0.5,	35869.5,          36843,	36658,	37602
0.95,	39209.1,  	  42328.75,	41423,	43277.9
0.99,	54295.1,  	68858.76,	56915,	63764.16
> Dynamodb API update

- jdbc/src/main/java/com/yahoo/ycsb/db/JdbcDBClient.java
- jdbc/src/test/java/com/yahoo/ycsb/db/JdbcDBClientTest.java
Changes to account for the proper field ordering. Now correctly inserting and updating field values so that they can be verified when using ```dataintegrity=true```. Fixes #132.
Main change here is that the StatementType is now built with an ordered listing of the fields for the statement. Some statements do not require this (scan, read, delete) and so just get an empty string. Also now able to be more precise in tests.
Each insert and update operation does have a little work to do to parse the fields for the operation. I did some performance comparisons and found the difference is not negligible, but also not dramatic or consistently slower.
||original|fixed|
|---|---|---|
|```[INSERT], AverageLatency(us)```|8748.63398|9805.35678|
|```[SCAN], …
```
> [jdbc] solidified field ordering

- hbase098/README.md
- hbase098/src/main/java/com/yahoo/ycsb/db/HBaseClient.java
- hbase10/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java
Changes in this pull request include
**For hbase098**
- Use HBase ``connection`` object to create ``table`` object
- Changes to make YCSB hbase tests run against a kerberized hbase cluster
- Update to README.txt to document the new parameters
**For hbase10**
- Changes to make YCSB hbase tests run against a kerberized hbase cluster
If users like to use **kerberos** keytab to make the connection to secure hbase cluster instead of using the ``user-id`` of the user running the test they can be passed using ``principal=keytab-principal-name`` and ``keytab=keytab=file`` properties.
**Update:** After the conversation in issue #322 , changes were made to **hbase098** and **hbase10** to use single HBase connection across all the threads when running a multi-thread test.
> [hbase] Changes to support secured HBase cluster 

- solr/src/test/resources/log4j.properties
the Solr tests are particularly chatty at the default log settings. this PR keeps them at INFO messages from the YCSB classes, but reduces them to ERROR from the Solr / jetty/ zk ones.
> [solr] tune down log output during tests.

- orientdb/README.md
- orientdb/src/main/java/com/yahoo/ycsb/db/OrientDBClient.java
All db connection and creation logic is the same, it is just pulled into
a synchronized method so that multiple threads run through the
connection process one at a time.
Fixes #571
> [orientdb] put db conn stuff in sync method

- hbase10/src/test/resources/hbase-site.xml
Currently YCSB can't be built on the machine running HBase cluster, because the local testing cluster tries to bind a master info server on the same port with the actual cluster's port. See the following output...
```
$ mvn clean package
...
-------------------------------------------------------
T E S T S
-------------------------------------------------------
Running com.yahoo.ycsb.db.HBaseClient10Test
...
2016/02/13 14:24:06 ERROR org.apache.hadoop.hbase.regionserver.HRegionServer  - Failed binding http info server to port: 16010
2016/02/13 14:24:06 ERROR org.apache.hadoop.hbase.MiniHBaseCluster  - Error starting cluster
java.lang.RuntimeException: Failed construction of Master: class org.apache.hadoop.hbase.master.HMasterAddress already in use
...
```
This is a bit annoying, so I turn …
> [hbase10] Turn off info servers during tests

- README.md
Yahoo! redesigned their website and our link to them is dead.
> [docs] Update link to old Yahoo! page due to site redesign.

- orientdb/README.md
- orientdb/src/main/java/com/yahoo/ycsb/db/OrientDBClient.java
- orientdb/src/test/java/com/yahoo/ycsb/db/OrientDBClientTest.java
Fixed two issues in the scan operation for OrientDBClient:
1. orientdb client was not handling fields being null which happens when you use ```readallfields=true```. I handled this the way a lot of other clients handle it, which is to just not iterate through the results.
2. There was a known issue where the scan operation would throw a NullPointerException if the scan range ran over the end of the record key range. This was because of a bad mixing of iterator implementations. This has now been fixed.
> Orientdb scan fix

- core/src/main/java/com/yahoo/ycsb/Client.java
This stems from my earlier adventures (see #407) trying to get a basic MySQL benchmark to run over JDBC, and improperly supplying the classpath but having no way to know what was upsetting the Java command line argument parser.
also "fixed" some indentation, because the alternative would have been to submit poorly indented code. Emacs is great for keeping indentation consistent, but if you're trying to match a file that isn't consistent, you're pretty much screwed. :)
> [client] Added basic command line argument error messages to Client.java

- accumulo/src/test/java/com/yahoo/ycsb/db/accumulo/AccumuloTest.java
The Accumulo tests don't properly initialize their mini cluster on windows,
so skip the tests entirely in that environment.
closes #617
> [accumulo] don't run Accumulo tests on windows build.

- orientdb/src/main/java/com/yahoo/ycsb/db/OrientDBClient.java
I was handling the null fields case with ```readallfields=true``` very poorly. The result was that it had to do no work with ```readallfields=true``` and so the performance was drastically different in a counterintuitive way.
This PR fixes that. @risdenk can we pull this into 0.7.0?
> [orientdb] fixed scan with readallfields

- bin/ycsb
- elasticsearch/README.md
- elasticsearch/pom.xml
- elasticsearch/src/main/java/com/yahoo/ycsb/db/ElasticsearchClient.java
- elasticsearch/src/test/java/com/yahoo/ycsb/db/ElasticsearchClientTest.java
This pull request fixes all instances of the name "ElasticSearch" to "Elasticsearch" (the official name of the project) and bumps the Elasticsearch version from version 2.1.1 to version 2.2.0 (the latest stable version of Elasticsearch).
> Elasticsearch cleanup

- core/src/main/java/com/yahoo/ycsb/Utils.java
- core/src/test/java/com/yahoo/ycsb/TestUtils.java
These will be used for #653 to write timestamps and numeric values
to the ByteIterator maps.
> [core] Add byte to double and long conversion methods to Utils.

- dynamodb/pom.xml
- dynamodb/src/main/java/com/yahoo/ycsb/db/DynamoDBClient.java
- dynamodb/src/main/java/com/yahoo/ycsb/db/package-info.java
Update of PR #481. Relates to #267
> [dynamodb] Checkstyle updates for DynamoDB.

- core/src/main/java/com/yahoo/ycsb/generator/UnixEpochTimestampGenerator.java
- core/src/test/java/com/yahoo/ycsb/generator/TestUnixEpochTimestampGenerator.java
Tied to generating time series workloads: https://github.com/brianfrankcooper/YCSB/issues/653
> [core] Add a UnixEpochTimestampGenerator

- s3/src/main/java/com/yahoo/ycsb/db/S3Client.java
I encountered the following exception. 
S3Object opened in getS3ObjectAndMetadata() should be closed to avoid this exception.
```
2016-03-10 15:55:14:077 50 sec: 49 operations; 0 current ops/sec; est completion in 16 minutes [UPDATE: Count=0, Max=0, Min=9223372036854775807, Avg=, 90=0, 99=0, 99.9=0, 99.99=0] 
Mar 10, 2016 3:55:23 PM com.amazonaws.http.AmazonHttpClient executeHelper
INFO: Unable to execute HTTP request: Timeout waiting for connection from pool
org.apache.http.conn.ConnectionPoolTimeoutException: Timeout waiting for connection from pool
at org.apache.http.impl.conn.PoolingClientConnectionManager.leaseConnection(PoolingClientConnectionManager.java:226)
at org.apache.http.impl.conn.PoolingClientConnectionManager$1.getConnection(PoolingClientConnectionManager.java:195)
at …
```
> [S3] Close opened S3Object

- cassandra/src/main/java/com/yahoo/ycsb/db/CassandraClient10.java
- cassandra/src/main/java/com/yahoo/ycsb/db/CassandraClient7.java
- cassandra/src/main/java/com/yahoo/ycsb/db/CassandraClient8.java
clear containers before we use them rather than after, so that in the case of
exceptions we can recover.
closes #127
> [cassandra] properly clear cached containers.

- cassandra2/pom.xml
- cassandra2/src/test/java/com/yahoo/ycsb/db/CassandraCQLClientTest.java
- pom.xml
update the work in #614 so that maven skips tests under jdk7 and uses a profile to turn them on under jdk8.
> Update cassandra2-cql driver to only run tests on jdk8

- cassandra2/pom.xml
- cassandra2/src/test/java/com/yahoo/ycsb/db/CassandraCQLClientTest.java
- pom.xml
> Update cassandra2-cql layer to use the new driver version.

- elasticsearch/README.md
- elasticsearch/pom.xml
- elasticsearch/src/main/java/com/yahoo/ycsb/db/ElasticsearchClient.java
- elasticsearch/src/test/java/com/yahoo/ycsb/db/ElasticsearchClientTest.java
This pull request is a major tidying up of the Elasticsearch 
- upgrade the dependency to Elasticsearch 2.3.1, the latest stable version
- remove unneeded settings
- fix/cleanup index creation
- fix local/remote node settings
- cleanup comments, docs, code
- add settings for `number_of_shards`, `number_of_replicas`
These bindings work against an embedded local node and against a remote cluster and work on against *all* released versions of Elasticsearch in the 2.x series.
> [elasticsearch] Elasticsearch improvements

- elasticsearch/src/main/java/com/yahoo/ycsb/db/ElasticsearchClient.java
This commit fixes a race condition that exists between the shards being
ready to serve requests and the execution of the workload.
> [elasticsearch] Fix race condition

- bin/ycsb
- couchbase2/README.md
- couchbase2/pom.xml
- couchbase2/src/main/java/com/yahoo/ycsb/db/couchbase2/Couchbase2Client.java
- couchbase2/src/main/java/com/yahoo/ycsb/db/couchbase2/package-info.java
- distribution/pom.xml
- pom.xml
Hi everyone,
this PR adds support for Couchbase Server using the new SDK (version 2.x). It includes support for the N1QL query language amongst other things. Note that the 1.x SDK (used in the `couchbase` driver) is still supported, but won't get new features - so all of the good stuff is and will go into this one.
Thanks!
Michael
> [couchbase2] Add Support for Couchbase SDK 2.x

- hbase10/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java
Fix broken synchronization meant to guard against over-creation
of cluster connection instances on startup when multiple threads.
> [hbase10] Still too many threads #691.

- .travis.yml
Closes #676.
This should enable testing Cassandra instead of it being skipped. Will need to check the Travis run for this PR.
> [build] Added Oracle JDK 8 to .travis.yml

- couchbase2/README.md
- couchbase2/src/main/java/com/yahoo/ycsb/db/couchbase2/Couchbase2Client.java
This changeset adds 2 config params which can be tweaked to enable
and print both the network latency and runtime metrics to the
configured logger.
> [couchbase2] Allow to log latency & runtime metrics.

- core/src/main/java/com/yahoo/ycsb/Client.java
- core/src/main/java/com/yahoo/ycsb/Utils.java
- core/src/main/java/com/yahoo/ycsb/measurements/Measurements.java
- core/src/test/java/com/yahoo/ycsb/TestUtils.java
- workloads/workload_template
when the status thread is enabled. This tracks the GC count, thread count,
memory used and average system load (if implemented) over time.
Related to #717
> [core] Add the "measurement.trackjvm" property to measure JVM statistics

- bin/ycsb
Fix checking of argparse module and custom check_output to not return None for err.output.
Fixes #708
> [scripts] Fix bin/ycsb for Python 2.6 and bin/ycsb check_output

- core/src/main/java/com/yahoo/ycsb/Client.java
- core/src/main/java/com/yahoo/ycsb/Utils.java
- core/src/test/java/com/yahoo/ycsb/TestUtils.java
the JVM spent in GC. It now prints the time and percent of time in
the final output.
Also fix cases where the garbage collector implementation returns
-1 if the count or time isn't implemented.
> [core] Add the Utils.getGCTotalTime() method for showing how long

- googlebigtable/src/main/java/com/yahoo/ycsb/db/GoogleBigtableClient.java
> [bigtable] Bigtable uses 1ms granularity.

- riak/README.md
- riak/src/main/java/com/yahoo/ycsb/db/riak/RiakKVClient.java
- riak/src/main/java/com/yahoo/ycsb/db/riak/RiakUtils.java
- riak/src/main/resources/riak.properties
I think I might have find a good compromise solution for allowing strong-consistent `scan` transactions. 
So, the idea I had was the following: considering that Riak allows to utilize _secondary indexes_ only for eventually-consistent bucket-types, I've created one of these (called `fakeBucketType`) just to exploit this property. In practice, I've modified the `insert` function to make sure that, beside inserting the actual record to the proper bucket-type (which is the one called `ycsb` by default), a 1-byte record (which is the minimum allowed size) **with the same key as the latter** was stored in the `fakeBucketType` just to keep track of its secondary index. Then, for the scan transactions, I've changed the source of the secondary indexes search operation to `fakeBucketType` to …
> [riak] Added a workaround to allow strong-consistent scan transactions.

- elasticsearch/pom.xml
This commit bumps the version of the Elasticsearch dependency for the
Elasticsearch binding to version 2.3.2.
> [elasticsearch] Bump version to 2.3.2

- mongodb/README.md
- mongodb/src/main/resources/logback.xml
In response to #752, I thought it might be a good idea to restrict the mongodb driver logging by default. In the README I provided instructions on how to manipulate the log level without rebuilding if anyone decides they do want all the logs.
> [mongodb] added logback.xml to mongodb module

- mongodb/src/main/java/com/yahoo/ycsb/db/AsyncMongoDbClient.java
in #746 it was found that when using the `mongodb-async` binding with a write concern of `w=0` then update operations will always return `-1` which in turn reports an operation status of `NOT_FOUND`.
Since you cannot tell what the result of the update operation is whne you fire and forget, it is reasonable to just return success for all update operations in the `mongodb-async` binding when using a write concern of `w=0`.
> [mongodb] return OK on updates with w=0

- README.md
- bin/bindings.properties
- bin/ycsb.bat
- bin/ycsb.sh
I've been thinking for a while that it'd be better to use a unix shell script or windows batch script to run YCSB. It seems to me that the python script has been mostly sufficient but sometimes problematic. I've seen users run into issues with wrong python versions, not having python installed, and also not understanding the requirement to have python installed.
My hope was that a unix script or windows batch would make things easier for the end user. I had these following additional goals:
-     create a single point of update when new bindings are added
-     the linux script should also run under cygwin on windows
-     work with both release and source checkout
-     model after tomcat
Here are the files I've added:
- binding.properties - This file contains all the binding names and …
> Shell scripts to run YCSB.

- couchbase2/README.md
- couchbase2/src/main/java/com/yahoo/ycsb/db/couchbase2/Couchbase2Client.java
- pom.xml
This PR has a dependency update.
Atop that, there's a change to the query to use RAW results.  More in the commit message there.
> [couchbase2] Update Java SDK version, query for workloade

- couchbase2/src/main/java/com/yahoo/ycsb/db/couchbase2/Couchbase2Client.java
When dataintegrity=true, no field values in passed to verifyRow() for verify and keep on getting error.
> [couchbase2] logical error in decode()

- bin/bindings.properties
The new Rados binding from 0.10.0 is missing an entry in the properties file used to handle the platform specific scripts.
If someone can review quickly, I'm fine with pulling this into the release for #772.
> [scripts] Rados missing from properties file for new platform-specific scripts.

- jdbc/src/main/java/com/yahoo/ycsb/db/JdbcDBCreateTable.java
The name of primary key in the original statement conflicts with reserved keyword and is inconsistent with the specified table schema in the documentation.
Fixed.
> [jdbc]Fix bug in constructing CREATE TABLE SQL statement

- elasticsearch/README.md
- elasticsearch/pom.xml
- elasticsearch/src/main/java/com/yahoo/ycsb/db/ElasticsearchClient.java
- elasticsearch/src/test/java/com/yahoo/ycsb/db/ElasticsearchClientTest.java
This pull request enhances some aspects of the Elasticsearch binding:
- explain embedded vs. remote mode
- change test runner to JUnit
- require `path.home` when running in embedded mode
- version bump to 2.3.4
> Various Elasticsearch improvements

- .gitignore
This commit adds the IntelliJ ipr extension to .gitignore. These project
files are created when running the Maven goal idea:idea.
> Add additional IntelliJ project file to Git ignore

- mongodb/src/main/resources/logback.xml
> [mongodb] correct placement of xml header on logback configs.

- core/src/main/java/com/yahoo/ycsb/BasicDB.java
- core/src/main/java/com/yahoo/ycsb/RandomByteIterator.java
Exceptions are cheap but not that cheap. This will save an exception whenever the byte[] is not a multiple of 6. e.g. 100 bytes
> Optimise fillBytesImpl so it doesn't trigger an Exception on every byte[] generated.

- couchbase2/README.md
- couchbase2/src/main/java/com/yahoo/ycsb/db/couchbase2/Couchbase2Client.java
Time to live (TTL) is the amount of time until a document expires in Couchbase Server. Having this property will help user not to clean up DB manually.
> [couchbase2] Added support for ttl in Couchbase2

- elasticsearch/pom.xml
This commit upgrades the Elasticsearch dependency from version 2.3.4 to
version 2.4.0.
> [elasticearch] upgrade to version 2.4.0

- cassandra/pom.xml
- cassandra/src/test/java/com/yahoo/ycsb/db/CassandraCQLClientTest.java
Added slf4j-simple so we can see what is happening during the Cassandra tests and get an idea why it fails. The timeout was increased from 10 seconds to 120 seconds. I tried 60 seconds but on Docker it still failed. Bumping up to 120 seems to have worked.
Fixes #495
> [cassandra] Increase Cassandra test timeout and add logging for test failures

- core/src/main/java/com/yahoo/ycsb/DBWrapper.java
- core/src/main/java/com/yahoo/ycsb/Status.java
- core/src/main/java/com/yahoo/ycsb/workloads/CoreWorkload.java
- core/src/test/java/com/yahoo/ycsb/TestStatus.java
- jdbc/README.md
- jdbc/src/main/java/com/yahoo/ycsb/db/JdbcDBClient.java
- jdbc/src/main/java/com/yahoo/ycsb/db/StatementType.java
- jdbc/src/main/java/com/yahoo/ycsb/db/flavors/DBFlavor.java
- jdbc/src/main/java/com/yahoo/ycsb/db/flavors/DefaultDBFlavor.java
- jdbc/src/main/java/com/yahoo/ycsb/db/flavors/PhoenixDBFlavor.java
- jdbc/src/main/java/com/yahoo/ycsb/db/flavors/package-info.java
- jdbc/src/test/java/com/yahoo/ycsb/db/JdbcDBClientTest.java
A couple of things included in this PR. Happy to split them out if that is preferred. I just came across all of these in some recent testing.
* Builds on @enis's commit which didn't make it upstream. Implements a "flavor" for Apache Phoenix (which only provides `UPSERT` to write data, no `INSERT`)
* Some basic cleanup of JdbcDBClient (rip out all of the flavors logic into their own files)
* De-couples batching APIs and autocommit. Again, trying to support Phoenix better, but not break JDBC semantics.
* Finally, fixes an issue with the existing batching support where the CoreWorkload treated `Status.BATCHED_OK` as an error (not the same as `Status.OK`)
> [jdbc] Assorted cleanup/fixes around batching and supporting different databases

- checkstyle.xml
- pom.xml
- solr/pom.xml
Checkstyle redundant throws is unreliable and is removed from newest version of checkstyle.
* https://github.com/checkstyle/checkstyle/issues/5#issuecomment-52593242
* Updated checkstyle and removed redundant throws from checkstyle.xml
Solr 5.x doesn't work with JDK 9.
* Skip the tests on JDK 9
* solr pom.xml had spaces and tabs.
* Solr 6.x supports JDK 9 - PR #716 
Relates to #705
> [jdbc, solr] Fix JDBC checkstyle and skip Solr 5.x with JDK 9

- bin/bindings.properties
- bin/ycsb
- distribution/pom.xml
- pom.xml
- solr/src/main/java/com/yahoo/ycsb/db/solr/SolrClient.java
- solr/src/main/java/com/yahoo/ycsb/db/solr/package-info.java
- solr/src/test/java/com/yahoo/ycsb/db/solr/SolrClientBaseTest.java
- solr/src/test/java/com/yahoo/ycsb/db/solr/SolrClientCloudTest.java
- solr/src/test/java/com/yahoo/ycsb/db/solr/SolrClientTest.java
- solr6/README.md
- solr6/pom.xml
- solr6/src/main/java/com/yahoo/ycsb/db/solr6/SolrClient.java
- solr6/src/main/java/com/yahoo/ycsb/db/solr6/package-info.java
- solr6/src/main/resources/log4j.properties
- solr6/src/test/java/com/yahoo/ycsb/db/solr6/SolrClientBaseTest.java
- solr6/src/test/java/com/yahoo/ycsb/db/solr6/SolrClientCloudTest.java
- solr6/src/test/java/com/yahoo/ycsb/db/solr6/SolrClientTest.java
- solr6/src/test/resources/log4j.properties
- solr6/src/test/resources/solr_config/schema.xml
- solr6/src/test/resources/solr_config/solrconfig.xml
> [solr,solr6] Add Solr 6 binding

- bin/bindings.properties
- bin/ycsb
- checkstyle.xml
- core/src/main/java/com/yahoo/ycsb/workloads/RestWorkload.java
- distribution/pom.xml
- pom.xml
- rest/README.md
- rest/pom.xml
- rest/src/main/java/com/yahoo/ycsb/webservice/rest/RestClient.java
- rest/src/main/java/com/yahoo/ycsb/webservice/rest/package-info.java
- rest/src/test/java/com/yahoo/ycsb/webservice/rest/IntegrationTest.java
- rest/src/test/java/com/yahoo/ycsb/webservice/rest/ResourceLoader.java
- rest/src/test/java/com/yahoo/ycsb/webservice/rest/RestClientTest.java
- rest/src/test/java/com/yahoo/ycsb/webservice/rest/RestTestResource.java
- rest/src/test/java/com/yahoo/ycsb/webservice/rest/Utils.java
- rest/src/test/resources/WebContent/index.html
- rest/src/test/resources/error_trace.txt
- rest/src/test/resources/trace.txt
- rest/src/test/resources/workload_rest
Please review. Touched only the absolutely necessary files required. CheckStyle formatting is followed, unit tests created, build passes.
> Added Rest Client Module to benchmark Restful Web Services

- orientdb/README.md
- orientdb/src/main/java/com/yahoo/ycsb/db/OrientDBClient.java
- orientdb/src/test/java/com/yahoo/ycsb/db/OrientDBClientTest.java
- pom.xml
Several mistakes in OrienDBClient (mostly related to initialization in multithreaded loads) were fixed.
> [orientdb] OrientDB was updated to 2.2.10 and bugs fixed

- jdbc/README.md
- jdbc/src/main/conf/db.properties
- jdbc/src/main/conf/h2.properties
I was going through jdbc bindings (for integration with cockroachdb) and found some inconsistencies:
1. The README mentions that a workload file can be supplied to com.yahoo.ycsb.db.JdbcDBCreateTable. However there's nothing in the class which makes use of it. I assume it's unnecessary.
2. Update the property key for jdbc driver from "jdbc.driver" to "db.driver" according to JdbcDBClient.DRIVER_CLASS.
> Update README and sample config file for jdbc

- kudu/README.md
- kudu/pom.xml
- kudu/src/main/java/com/yahoo/ycsb/db/KuduYCSBClient.java
- kudu/src/main/java/com/yahoo/ycsb/db/package-info.java
- kudu/src/main/resources/log4j.properties
- pom.xml
This updates Kudu to the latest released client version, improves table partitioning, and switches debug logging to use slf4j.  Further details are in the commit messages.
> [kudu] Update Kudu binding to 1.1.0, use slf4j for logging, improve table partitioning

- core/src/main/java/com/yahoo/ycsb/BasicDB.java
- core/src/main/java/com/yahoo/ycsb/ByteArrayByteIterator.java
- core/src/main/java/com/yahoo/ycsb/ByteIterator.java
- core/src/main/java/com/yahoo/ycsb/DB.java
- core/src/main/java/com/yahoo/ycsb/DBFactory.java
- core/src/main/java/com/yahoo/ycsb/DBWrapper.java
- core/src/main/java/com/yahoo/ycsb/GoodBadUglyDB.java
- core/src/main/java/com/yahoo/ycsb/InputStreamByteIterator.java
- core/src/main/java/com/yahoo/ycsb/RandomByteIterator.java
- core/src/main/java/com/yahoo/ycsb/Status.java
- core/src/main/java/com/yahoo/ycsb/StringByteIterator.java
- core/src/main/java/com/yahoo/ycsb/TerminatorThread.java
- core/src/main/java/com/yahoo/ycsb/UnknownDBException.java
- core/src/main/java/com/yahoo/ycsb/Workload.java
- core/src/main/java/com/yahoo/ycsb/WorkloadException.java
- core/src/main/java/com/yahoo/ycsb/package-info.java
> [core] Fix checkstyle for Core miscellaneous

- dynamodb/pom.xml
- dynamodb/src/main/java/com/yahoo/ycsb/db/DynamoDBClient.java
Enabled enforcing and a few whitespace changes. Relates to #267
> [dynamodb] Enforce checkstyle for DynamoDB binding

- asynchbase/src/main/java/com/yahoo/ycsb/db/AsyncHBaseClient.java
- asynchbase/src/test/java/com/yahoo/ycsb/db/AsyncHBaseTest.java
- cassandra/src/test/java/com/yahoo/ycsb/db/CassandraCQLClientTest.java
- checkstyle.xml
- core/src/main/java/com/yahoo/ycsb/workloads/CoreWorkload.java
- core/src/main/java/com/yahoo/ycsb/workloads/RestWorkload.java
- hbase098/src/main/java/com/yahoo/ycsb/db/HBaseClient.java
- hbase10/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java
- hbase10/src/test/java/com/yahoo/ycsb/db/HBaseClient10Test.java
- kudu/src/main/java/com/yahoo/ycsb/db/KuduYCSBClient.java
> [core] Fix checkstyle for CoreWorkload

- core/src/main/java/com/yahoo/ycsb/measurements/Measurements.java
- core/src/main/java/com/yahoo/ycsb/measurements/OneMeasurement.java
- core/src/main/java/com/yahoo/ycsb/measurements/OneMeasurementHdrHistogram.java
- core/src/main/java/com/yahoo/ycsb/measurements/OneMeasurementHistogram.java
- core/src/main/java/com/yahoo/ycsb/measurements/OneMeasurementRaw.java
- core/src/main/java/com/yahoo/ycsb/measurements/OneMeasurementTimeSeries.java
- core/src/main/java/com/yahoo/ycsb/measurements/TwoInOneMeasurement.java
- core/src/main/java/com/yahoo/ycsb/measurements/exporter/JSONArrayMeasurementsExporter.java
- core/src/main/java/com/yahoo/ycsb/measurements/exporter/JSONMeasurementsExporter.java
- core/src/main/java/com/yahoo/ycsb/measurements/exporter/MeasurementsExporter.java
- core/src/main/java/com/yahoo/ycsb/measurements/exporter/TextMeasurementsExporter.java
- core/src/main/java/com/yahoo/ycsb/measurements/exporter/package-info.java
- core/src/main/java/com/yahoo/ycsb/measurements/package-info.java
> [core] Fix checkstyle for measurements package

- hbase098/pom.xml
- hbase098/src/main/java/com/yahoo/ycsb/db/HBaseClient.java
- hbase098/src/main/java/com/yahoo/ycsb/db/package-info.java
Relates to #267 and supersedes #484
> [hbase098] Fix checkstyle for HBase 0.98.x binding

- aerospike/src/main/java/com/yahoo/ycsb/db/AerospikeClient.java
The original Aerospike interface layer was created when the REPLACE_ONLY option was not available.  This provides a policy more in line with the policies that other databases have implemented their interface layers.
> Change the write policy to REPLACE_ONLY

- accumulo/README.md
- accumulo/src/main/java/com/yahoo/ycsb/db/accumulo/AccumuloClient.java
* Expand on the README, covering table creation and best-practices for table config
* Avoid unnecessary `Text` object creations (in loops and instead of `byte[]` usage)
* Use a `ConcurrentHashMap` to better match the DB API
* Fix error messages and always call `printStackTrace()` on exceptions
* Use `BATCHED_OK` instead of `OK` in `insert()` (more correct)
Tagging some potentially interested folks.. @busbey @madrob @keith-turner
> A general "refresh" to the Accumulo binding

- memcached/README.md
- memcached/src/main/java/com/yahoo/ycsb/db/MemcachedClient.java
Adding support for memcached binary protocol as described in
https://github.com/memcached/memcached/blob/master/doc/protocol.txt.
Protocol can be set via memcached.protocol property of YCSB memcached workload. if specified
protocol must be "binary" or "text". If unspecified text version is used.
> [memcached] support binary protocol

- bin/bindings.properties
- bin/ycsb
- distribution/pom.xml
- hbase12/README.md
- hbase12/pom.xml
- hbase12/src/main/java/com/yahoo/ycsb/db/hbase12/HBaseClient12.java
- hbase12/src/main/java/com/yahoo/ycsb/db/hbase12/package-info.java
- hbase12/src/test/java/com/yahoo/ycsb/db/hbase12/HBaseClient12Test.java
- hbase12/src/test/resources/hbase-site.xml
- hbase12/src/test/resources/log4j.properties
- pom.xml
Adds a new module that reduces the footprint of third party jars by relying on the shaded artifact provided by the apache hbase project as of 1.2.0.
A current limitation of the shaded clients is that they can't be tested using the minicluster that ships with HBase. So for now, this patch relies on the `hbase10` module for implementation and testing. The `hbase12` module and client just do pass through to the ycsb client-side logic in that module.
> [hbase12] Add HBase 1.2+ specific client that relies on the shaded client artifact provided by those versions.

- s3/src/main/java/com/yahoo/ycsb/db/S3Client.java
The S3Client does not read the whole object.
The problem is in the call "objectData.read(inputStreamToByte, 0, sizeOfFile)" inside readFromStorage method. This call is returning only the beginning of the object if the object is long enough.
> [s3] S3Client could not estimate read perfomance correctly (#994)

- .travis.yml
- asynchbase/pom.xml
- elasticsearch5/pom.xml
- pom.xml
* remove oracle jdk7 per travis-ci/travis-ci#7884
* stop ES test cluster spin-up during the install phase
* temporarily remove the riak service on travis
- currently fails w/o details
- http://docs.basho.com/ fails to load, so I can't spin up a test node locally.
> [travis] get travis back to happy

- .travis.yml
- accumulo/pom.xml
- hbase098/pom.xml
- pom.xml
- solr/pom.xml
- solr6/pom.xml
Relates to #705 
I had to also:
* upgrade the `maven-compiler-plugin` to 3.6.2 or later
* https://cwiki.apache.org/confluence/display/MAVEN/Java+9+-+Jigsaw
* Exclude `jdk.tools` from all Hadoop dependencies (especially transitive)
* avoids `Could not find artifact jdk.tools:jdk.tools:jar:1.6 at specified path /usr/lib/jvm/java-9-oracle/../lib/tools.jar`
> [travis] Travis CI add oraclejdk9

- jdbc/src/main/java/com/yahoo/ycsb/db/JdbcDBClient.java
- jdbc/src/main/java/com/yahoo/ycsb/db/JdbcDBCreateTable.java
Supersedes PR #797. Updated JavaDocs
> [jdbc] Use `TEXT` for fields instead of VARCHAR

- bin/bindings.properties
- bin/ycsb
- distribution/pom.xml
- pom.xml
* remove mapkeeper and voldemort from command help, since we don't build them
* fix ordering of modules in root pom
closes #328
> [scripts, core] cleanup bindings

- s3/src/main/java/com/yahoo/ycsb/db/S3Client.java
ObjectMetadata is available from S3Object.getObjectMetadata().
We don't need to send a separate GetObjectMetadata Request (an
HTTP HEAD request), in order to get the metadata. With this patch, 
read performance will be doubled.
Signed-off-by: Xing Lin <Xing.Lin@netapp.com>
> Remove unnecessary getObjectMetadata() from getS3ObjectAndMetadata()

- core/src/main/java/com/yahoo/ycsb/workloads/TimeSeriesWorkload.java
- core/src/test/java/com/yahoo/ycsb/workloads/TestTimeSeriesWorkload.java
When the TimeSeriesWorkload was run with fieldcount=1 and tagcount=1 and tagcardinality=1 the data generated always had the same timestamp. This commit fixes this behavior by forcing a tag rollover when there is only one tag.
> [core][timeseries] Fix timestamp generation when one tag with cardinality one.

- bin/bindings.properties
- bin/ycsb
- bin/ycsb.bat
- bin/ycsb.sh
- distribution/pom.xml
- hbase14/README.md
- hbase14/pom.xml
- hbase14/src/main/java/com/yahoo/ycsb/db/hbase14/HBaseClient14.java
- hbase14/src/main/java/com/yahoo/ycsb/db/hbase14/package-info.java
- hbase14/src/test/java/com/yahoo/ycsb/db/hbase14/HBaseClient14Test.java
- hbase14/src/test/resources/hbase-site.xml
- hbase14/src/test/resources/log4j.properties
- hbase20/README.md
- hbase20/pom.xml
- hbase20/src/main/java/com/yahoo/ycsb/db/hbase20/HBaseClient20.java
- hbase20/src/main/java/com/yahoo/ycsb/db/hbase20/package-info.java
- hbase20/src/test/java/com/yahoo/ycsb/db/hbase20/HBaseClient20Test.java
- hbase20/src/test/resources/hbase-site.xml
- hbase20/src/test/resources/log4j.properties
- pom.xml
Updates for version changes in the Apache HBase project
* deprecate 0.98 and 1.0 clients so we can remove them later.
* add an HBase 1.4 client jar specific binding, in anticipation of the HBase project making that their stable version
* add an HBase 2.0 client jar specific binding based on the HBase 2.0.0-beta-2 release to ease folks evaluating that release
The latter two follow the same pattern as the HBase 1.2 binding where we reuse the implementation from the hbase10 binding and just swap in the shaded client jars.
> [hbase098, hbase10, hbase14, hbase20] HBase client updates

- geode/README.md
- geode/src/main/java/com/yahoo/ycsb/db/GeodeClient.java
- pom.xml
Geode 1.3 changed some of it's internals. The geode binding was using an
internal Geode class which means it won't compile against later versions
of geode.
> [geode] Ensure geode client will work with v1.3 by removing references to internal classes

- hbase10/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java
- module previously had an undeclared dependency on guava
- removed VisibleForTesting in favor of a comment
- removed Preconditions.checkNotNull in favor of NPE through use
closes #1136
> [hbase10] Remove use of guava

- googlebigtable/pom.xml
- googlebigtable/src/main/java/com/yahoo/ycsb/db/GoogleBigtableClient.java
- hbase10/README.md
- pom.xml
Update Bigtable to 1.0:
- update package name to use the new 1.x artifacts
- remove explicit tcnative dep, it is now transitively pulled into bigtable-hbase-1.x and is shaded into into bigtable-hbase-1.x-hadoop
- remove AsyncExecutor flushing, flushing the bulk mutation should be enough
- update hbase10 instructions to use bigtable-hbase-1.x-hadoop
@sduskis & @mbrukman please take a look
> update bigtable to 1.0

- bin/ycsb.bat
- bin/ycsb.sh
- core/pom.xml
Fixes #877.
I don't know if this is the best way to solve this. Basically the core module's parent was root before. I made it binding parent so that it will pickup the necessary assembly plugin and create the lib directory. I'm not really familiar with Maven module parents and dependencies.
> [core] Fix ycsb.sh and ycsb.bat missing core dependencies

- pom.xml
@sduskis, @igorbernstein2 — please review and let me know if you have any thoughts on this.
> Update Bigtable client version to 1.3.0 (latest).

- cassandra/src/main/java/com/yahoo/ycsb/db/CassandraCQLClient.java
- cassandra/src/test/java/com/yahoo/ycsb/db/CassandraCQLClientTest.java
Addressing issue #458. The PreparedStatement is created and cached following the same approach as in JdbcDBClient. Here are the numbers before and after the use of PreparedStatement:
Apache Cassandra version: 3.11.1, replication_factor = 3, QUORUM consistency level
Server: 3-node Google Cloud Platform (GCP) n1-standard-16 machine, 16 VCPU's, 60GB memory, 2 x 375 GB direct attached SSD
YCSB parameter: recordcount=1000000, operationcount=10000000, maxexecutiontime=90
**Before:**
Workload   : Throughput(ops/sec) - OpType & AverageLatency(us)
workload a : 64956.256567473 - [READ]: 4282.700504426243 [UPDATE]: 3346.0443676539962
workload b : 63345.63794747335 - [READ]: 3949.758514786955 [UPDATE]: 3189.5031351661996
workload c : 64365.03672249063 - [READ]: 3849.324261325788
workload d : …
> [cassandra] Update CassandraCQLClient to use PreparedStatement for better performance

- .editorconfig
- core/src/main/resources/project.properties
- elasticsearch5/src/main/resources/log4j2.properties
- elasticsearch5/src/test/java/com/yahoo/ycsb/db/elasticsearch5/ElasticsearchIntegTestBase.java
- kudu/src/main/resources/log4j.properties
- mapkeeper/README.md
- nosqldb/README.md
- orientdb/src/main/resources/log4j.properties
- rest/pom.xml
- rest/src/test/resources/WebContent/index.html
- s3/src/main/conf/s3.properties
- solr/src/main/resources/log4j.properties
- solr6/src/main/resources/log4j.properties
While getting ready to cut the staging branch to run the 0.14.0 release, I hit a bunch of "files don't have header" errors from the rat check
> [licensing] add missing headers called out by the RAT plugin.

- core/src/main/java/com/yahoo/ycsb/workloads/CoreWorkload.java
Allow user to specify the following parameters in `CoreWorkload` 
- the minimum field length for request generation via property  `minfieldlength`
- the minimum number of records to scan via property `minscanlength`
The original value of both parameters ("1") is retained as their default values.
> [core] Add options for user-specified min field length

- bin/bindings.properties
- bin/ycsb
- distribution/pom.xml
- pom.xml
- rocksdb/README.md
- rocksdb/pom.xml
- rocksdb/src/main/java/com/yahoo/ycsb/db/rocksdb/RocksDBClient.java
- rocksdb/src/main/java/com/yahoo/ycsb/db/rocksdb/package-info.java
- rocksdb/src/test/java/com/yahoo/ycsb/db/rocksdb/RocksDBClientTest.java
This adds support for RocksDB via RocksJava binding.
> [rocksdb] Added support for RocksDB Java API

- bin/bindings.properties
- bin/ycsb
- distribution/pom.xml
- foundationdb/README.md
- foundationdb/pom.xml
- foundationdb/src/main/java/com/yahoo/ycsb/db/foundationdb/FoundationDBClient.java
- foundationdb/src/main/java/com/yahoo/ycsb/db/foundationdb/package-info.java
- pom.xml
Here is a new client for FoundationDB, which is based on the API version 5.1.7.
> [foundationdb] add a new client for FoundationDB

- bin/ycsb
This PR completes the elasticsearch5-rest binding in ./bin/ycsb.
> [elasticsearch5-rest] add forgotten elasticsearch5-rest binding.

- .travis.yml
we'll try running openjdk an oraclejdk in parallel for a bit, and we don't see any differences just switch to openjdk entirely.
> [travis] drop deprecated oracle JDKs, add openjdk versions for jdk8 and jdk11

- core/src/main/java/com/yahoo/ycsb/workloads/CoreWorkload.java
- doc/coreproperties.html
- hbase/src/main/java/com/yahoo/ycsb/db/HBaseClient.java
By default YCSB names the database record fields as “field” + a number.
The new configuration option allows to replace the “field” prefix with
something shorter which affects the data storage size for schema-less databases.
> Added fieldnameprefix property

- bin/bindings.properties
Was set to `com.yahoo.ycsb.db.hbase14` package instead of `com.yahoo.ycsb.db.hbase20`.
> [hbase20] fix package in bindings

- orientdb/README.md
- orientdb/src/main/java/com/yahoo/ycsb/db/OrientDBClient.java
- pom.xml
This PR is based on the issue #1045, it fixes nullPointerExceptions with multiple Threads. During this I updated the dependencies to the newest version of OrientDB 2 (2.2.37) and added an example for remote connections to the readme
> [orientdb] fixed issue #1045, updated to orientdb version 2.2.37

- cassandra/README.md
- cassandra/src/main/java/com/yahoo/ycsb/db/CassandraCQLClient.java
Small change to add a new flag called useSSL.  It flag adds the ability to use secure connections. The default is "false" which is how the current driver connects.  Personally I think the default should be secure connections but I dont want to break compatibility.
> Adding the ability to connect to Cassandra using SSL connections.

- azurecosmos/README.md
- azurecosmos/src/main/java/com/yahoo/ycsb/db/AzureCosmosClient.java
- pom.xml
Updating Cosmos DB to the latest driver and removing flags for
features that are no longer used.  For examply myid was needed
when id only supported hash lookup.  Now id supports range index
so scan can be handled.
> Updating to the latest driver and removing flag that are no longer needed.

- hbase098/README.md
for whatever reason, the hbase client property for turning on client side buffering never got properly documented.
to add to the confusion, we do document a config used to tune client side buffering, but that config is ignored unless client side buffering is turned on. Also, it's used in one of our examples. :/
> [hbase098] document the client side buffering config.

- pom.xml
tested successfully current code with updated spanner/bigtable library in order to be more compatible with other more updated google cloud components and confirm it works with 0.16.0 YCSB.
used following settings:
./bin/ycsb load cloudspanner -P workloads/workloada -P cloudspanner.properties -p recordcount=1000
./bin/ycsb run cloudspanner -P workloads/workloada -P cloudspanner.properties -p operationcount=1000
table = usertable
zeropadding = 12
cloudspanner.instance = ycsb-instance
cloudspanner.database = ycsb-database
cloudspanner.readmode = query
cloudspanner.boundedstaleness = 0
cloudspanner.batchinserts = 1
./bin/ycsb load googlebigtable -P workloads/workloada -P googlebigtable.properties -p recordcount=1000
./bin/ycsb run googlebigtable -P workloads/workloada -P …
> [cloudspanner bigtable] update client library versions

- .travis.yml
- bin/bindings.properties
- bin/ycsb
- distribution/pom.xml
- pom.xml
- postgrenosql/README.md
- postgrenosql/conf/postgrenosql.properties
- postgrenosql/pom.xml
- postgrenosql/src/main/java/com/yahoo/ycsb/postgrenosql/PostgreNoSQLDBClient.java
- postgrenosql/src/main/java/com/yahoo/ycsb/postgrenosql/StatementType.java
- postgrenosql/src/main/java/com/yahoo/ycsb/postgrenosql/package-info.java
- postgrenosql/src/test/java/com/yahoo/ycsb/postgrenosql/PostgreNoSQLDBClientTest.java
@busbey: I hope to have addressed all suggested adaptions.
- Removed package information from testing.
- Added caching for the SQL Statements by using the Statement Class.
- Added additional information about code changes in the license part.
- Simplified test code (removed creation and deletion of test database, only use travis).
> [PostgreNoSQL] Added NoSQL support for PostgreSQL.

- core/src/main/java/com/yahoo/ycsb/ByteArrayByteIterator.java
- core/src/main/java/com/yahoo/ycsb/ByteIterator.java
- core/src/main/java/com/yahoo/ycsb/InputStreamByteIterator.java
- core/src/main/java/com/yahoo/ycsb/RandomByteIterator.java
- core/src/main/java/com/yahoo/ycsb/StringByteIterator.java
Method nextBuf is a clever hack that outperforms Random.nextBytes
but performs poorly for all other ByteIterator implementations
This commit moves it to RandomByteIterator and adds efficient
toArray implementations for other ByteIterator classes.
Also InputStreamByteIterator.reset method that unconditionally
throws UnsupportedOperationException is fixed
Benchmarks for this change is available at https://github.com/isopov/isopov-jmh/blob/master/src/main/java/com/sopovs/moradanen/jmh/ycsb/ByteIteratorBenchmark.java
> [core] Optimize toArray of all ByteIterators except RandomByteIterator

- geode/src/main/java/com/yahoo/ycsb/db/GeodeClient.java
- geode/src/main/java/com/yahoo/ycsb/db/package-info.java
Apache Geode is not in incubating state. References to this were removed from README with a previous commit but not from the code.
> Remove 'incubating' from references to Apache Geode

- core/src/main/java/com/yahoo/ycsb/workloads/CoreWorkload.java
I required to use the exponential distribution provided in YCSB and found that when running YCSB with `requestdistribution=exponential` was failing. After checking the source code, it seemed that the checks for the exponential was not in the correct place, so I just moved it a bit further down. 
Please share any feedback and explain if I'm making a mistake in my reasoning here.
> Enabling exponential distribution in Core Workload

- .travis.yml
Travis' jdk installer has started failing when setting up oracle jdk8:
```
Installing oraclejdk8
$ export JAVA_HOME=~/oraclejdk8
$ export PATH="$JAVA_HOME/bin:$PATH"
$ ~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"
install-jdk.sh 2019-05-02
Expected feature release number in range of 9 to 13, but got: 8
The command "~/bin/install-jdk.sh --target "/home/travis/oraclejdk8" --workspace "/home/travis/.cache/install-jdk" --feature "8" --license "BCL"" failed and exited with 3 during .
Your build has been stopped.
```
> [travis] drop unsupported oracle JDK8

- bin/bindings.properties
- bin/ycsb
- distribution/pom.xml
- pom.xml
- tablestore/README.md
- tablestore/conf/tablestore.properties
- tablestore/pom.xml
- tablestore/src/main/java/com/yahoo/ycsb/db/tablestore/TableStoreClient.java
- tablestore/src/main/java/com/yahoo/ycsb/db/tablestore/package-info.java
- tablestore/src/main/resources/log4j.properties
1. TableStore is a NoSQL service provided by Alibaba Cloud. [Link](https://www.alibabacloud.com/product/table-store)
2. Code, Guide of Howto is provided.
> [tablestore] Add binding for Alibaba Cloud's TableStore

- core/src/main/java/com/yahoo/ycsb/ClientThread.java
- core/src/main/java/com/yahoo/ycsb/StatusThread.java
- postgrenosql/conf/postgrenosql.properties
- tablestore/pom.xml
* #1249 missed headers when moving things out of Client.java
* #1242 missed header on a properties file is added
* #1286 missed header on the new pom file
> [core] add missing license headers.

- jdbc/README.md
fix formatting issues showing in the re-writing batched insert `db.url` example box
> [jdbc] Fix README formatting of example connection strings

- jdbc/src/main/java/com/yahoo/ycsb/db/JdbcDBClient.java
- jdbc/src/main/java/com/yahoo/ycsb/db/flavors/DBFlavor.java
- jdbc/src/main/java/com/yahoo/ycsb/db/flavors/DefaultDBFlavor.java
Fixing the syntax issue SQL Server faced during scan operation.
( Microsoft SQL Server doesn't support LIMIT statement, so I added a condition to use TOP instead when we are using jdbc-binding to benchmark SQL Server scan operation. )
> [jdbc] Add mssql support for scan operation

- pom.xml
- rocksdb/README.md
- rocksdb/src/main/java/site/ycsb/db/rocksdb/RocksDBClient.java
- rocksdb/src/test/java/site/ycsb/db/rocksdb/RocksDBOptionsFileTest.java
- rocksdb/src/test/resources/testcase.ini
This adds support to run RocksDB with a custom [options file](https://github.com/facebook/rocksdb/wiki/RocksDB-Options-File).
This also updates the RocksDB Maven artifact version to the latest (6.2.2).
> [rocksdb] add rocksdb.optionsfile property

- jdbc/src/main/java/site/ycsb/db/JdbcDBClient.java
- jdbc/src/main/java/site/ycsb/db/flavors/DBFlavor.java
- jdbc/src/main/java/site/ycsb/db/flavors/DefaultDBFlavor.java
Currently, the JDBC interface implements the Scan with:
- SELECT TOP for SQL Server
- ORDER BY ... LIMIT for others
Today, most databases use the ORDER BY ... FETCH FIRST ... ROWS which is the SQL standard since 2008. 
See [Markus Winand matrix](https://www.slideshare.net/MarkusWinand/modern-sql/120)
In this PR I kept the "sqlserver" boolean but renamed it "sqlserverScans" as it is used only for scans. And I added a "sqlansiScans" for the FETCH FIRST syntax.
For compatibility, I kept it at false, and enable it only when the driver contains "oracle" or "postgres" as these are the common databases supporting the SQL ANSI syntax. But actually only SQLite, MySQL and MariaDB need to use this LIMIT syntax in current versions.
In the future, it is probably better to check the product and version …
> [jdbc] Add support for SQL:2008 FETCH FIRST n ROWS ONLY for Scans

- core/src/main/java/site/ycsb/Client.java
Solving https://github.com/brianfrankcooper/YCSB/issues/1382
Previously, if you defined maxexecutiontime and not defined operationcount
parameter (or set operationcount=0), then you were able to run YCSB for a
given period of time and measure the number of operations you get during
the load test.
Since #1323 was merged, it it not possible to use operationcount=0, as
the thread count will be set to 0 in this case and no client thread will
be created. This PR makes it possible to use operationcount=0 again.
> [core] make it possible to use zero operation count again. (#1382)

- pom.xml
Reference: https://ignite.apache.org/download.cgi 
Without this patch, benchmarking fails for the latest version of Apache Ignite.
> [ignite] Updates ignite to latest version

- .travis.yml
- pom.xml
* Enforces Maven version to not be 3.6.2
* Travis CI uses Maven wrapper where we control the Maven version used
Fixes #1390
> Updates Travis Maven and enforces Maven version

- kudu/src/main/java/site/ycsb/db/KuduYCSBClient.java
- pom.xml
This patch makes sure clients are closed properly on cleanup.
I also updated to the latest client version (1.11.1).
> [kudu] Close clients on cleanup

- dynamodb/conf/dynamodb.properties
- dynamodb/pom.xml
- dynamodb/src/main/java/site/ycsb/db/DynamoDBClient.java
* Upgrade AWS SDK from version 1.10.48 to 1.11.812.
* Introduce a new configuration parameter, dynamodb.region, which
represents a valid AWS region code (see
https://docs.aws.amazon.com/AWSEC2/latest/UserGuide/using-regions-availability-zones.html#concepts-available-regions
for example). If specifying the region, it is not necessary to specify
the dynamodb.endpoint parameter.
* Introduce support for non-standard endpoints. Before this commit,
setting the endpoint to a non-standard one, like a proxy, but
ultimately connecting to a region different from 'us-east-1' would
lead to a credential errors due to bad signature:
ERROR site.ycsb.db.DynamoDBClient
-com.amazonaws.AmazonServiceException: Credential should be scoped to
a valid region, not 'us-east-1'.  (Service: AmazonDynamoDBv2; Status …
> [dynamodb] Improve endpoint and region config

- cloudspanner/pom.xml
- pom.xml
We were using a very old version of the cloud spanner client libraries. This PR updates to the latest version (2.0.1).
> [spanner] chore: updates spanner client lib to 2.0.1

- rocksdb/README.md
change mvn build target to just build rocksdb-binding. This also makes the build command to be consistent with these for other bindings.
> [rocksdb] change mvn build target

- postgrenosql/src/main/java/site/ycsb/postgrenosql/PostgreNoSQLDBClient.java
The first ResultSet.next() call to test if the ResultSet was empty moved the cursor without adding the resulting row to the YCSB result callback.
> Read ResultSet was not iterated correctly.

- core/src/main/java/site/ycsb/workloads/CoreWorkload.java
- kudu/README.md
- kudu/src/main/java/site/ycsb/db/KuduYCSBClient.java
Kudu binding only support hash partitioning now, this patch provide another type of partitioning: range partitioning, it can be configured in `kudu_partition_schema`.
> [kudu] Support range partitioning

- core/src/main/java/site/ycsb/workloads/CoreWorkload.java
- core/src/main/java/site/ycsb/workloads/TimeSeriesWorkload.java
Users would benefit if they would know exactly that their
flags take an effect.
> [core] print data integrity status is enabled

- bin/ycsb
Python2 has reached EOL, so we should port the ycsb to Python3.
The modification also makes the ycsb Python2 compatible.
> Port ycsb to Python3 and also make it Python2 compatible

- pom.xml
Spanner's client library was outdated. This PR updates the spanner client library version to the latest available version at this point.
> [Spanner] chore: Updates spanner client lib to 6.71.0

- cloudspanner/pom.xml
Add shaded maven plugin to resolve conflicts for spanner
> fix(cloudspanner): fix ProtoLiteUtils ClassNotFound issue at run time

- core/pom.xml
fixes #1480
As per https://github.com/HdrHistogram/HdrHistogram/issues/175, versions prior 2.1.10 dont work with newer jdks.
> upgrade hdrhistogram to support newer jdk versions

- bin/ycsb
The current python ycsb script drops `runtime` dependencies from the classpath. The script uses mvn dependency:build-classpath with includeScope=compile. The dependency plugin defines compile as compile + provided deps, which means that if a driver has a transitive runtime dep, it will be ignored.
This PR changes the classpath building to use dependency:list goal to dump all of the dependencies and excludes any test deps and then builds the classpath from that
> fix python ycsb script classpath building

- googlebigtable2/README.md
- googlebigtable2/src/main/java/site/ycsb/db/GoogleBigtable2Client.java
* update reads to read the latest cell version to align with hbase behavior
* add ability to specify a fixed timestamp to avoid unbounded growth of cell versions
> googlebigtable2: Update cell version handling

- core/src/main/java/site/ycsb/measurements/OneMeasurementHdrHistogram.java
The average latency sometime can be misleading due to the high tail latency. P50 would give more insights about how the system performs.
> Add P50 to progress status and result report.

- googlebigtable2/README.md
- googlebigtable2/src/main/java/site/ycsb/db/GoogleBigtable2Client.java
This ports an existing feature from the original googlebigtable driver
> googlebigtable2: add ability to statically size the channel pool

- cloudspanner/README.md
- cloudspanner/src/main/java/site/ycsb/db/cloudspanner/CloudSpannerClient.java
- pom.xml
It also adds option to use plainText communication. It is useful especially when running with experimental host. 
This change also upgrades YCSB to use latest version of cloud spanner java client.
> Add support for running YCSB with the experimental Host.
