workloads/workload_template

Included a template collecting all workload properties into a single file. It shows the defaults and explains usage.

Workload template

---

elasticsearch/src/main/java/com/yahoo/ycsb/db/ElasticSearchClient.java

The ability to connect to multiple elasticseach hosts in a cluster environment  using transport client is very useful where auto discovery is turned off. This will enable connecting to remote hots without starting a node on the client benchmarking machine.

TransportClient support for connecting to remote elastic search clusters

---

bin/ycsb
couchbase/README.md
couchbase/pom.xml
couchbase/src/main/java/com/yahoo/ycsb/db/CouchbaseClient.java
pom.xml

Rebased the changes from #136 for current master. fixes the ycsb-parent version number.
Of the open "add couchbase" issues, this one is ready to go as-is. merging this one will probably close #114 and #172, but we should make sure there isn't a functionality gap.

rebased PR136: "Adding support for Couchbase"

---

bin/ycsb
cassandra/pom.xml
cassandra/src/main/java/com/yahoo/ycsb/db/CassandraCQLClient.java
cassandra/src/main/java/com/yahoo/ycsb/db/CassandraClient7.java
pom.xml

PR from #145 rebased for current master with change to unrelated module removed.

rebased PR145: "Added Cassandra CQL binding"

---

core/src/main/java/com/yahoo/ycsb/Client.java

[client] clean up status message creation.

---

distribution/pom.xml
pom.xml

[voldemort] disable voldemort pending maven accessible artifacts.

---

tarantool/src/main/java/com/yahoo/ycsb/db/TarantoolClient.java

Issue #319: [tarantool] Error on scan operation and replace problems

---

aerospike/README.md
aerospike/pom.xml
aerospike/src/main/java/com/yahoo/ycsb/db/AerospikeClient.java
bin/ycsb
distribution/pom.xml
pom.xml

Hey guys,
We've been using YCSB quite a bit at Aerospike lately. It would be nice, if we could get support for our database into the upstream YCSB code.
Thomas

Support Aerospike

---

.gitignore
bin/ycsb
infinispan/README.md
infinispan/pom.xml
infinispan/src/main/conf/remote-cache.properties
infinispan/src/main/java/com/yahoo/ycsb/db/InfinispanRemoteClient.java
infinispan/src/main/java/com/yahoo/ycsb/db/RemoteCacheManagerHolder.java
infinispan/src/main/java/com/yahoo/ycsb/db/Status.java
pom.xml

rebased #228 to current master, added a follow on commit to fix the double-check idiom and went to a final release of the client.

rebased PR228: "Client-Server mode benchmark support for infinispan"

---

README.md

updates the example download url to use the 0.2.0 release.

[docs] update README for 0.2.0 release.

---

orientdb/pom.xml
orientdb/src/main/java/com/yahoo/ycsb/db/OrientDBClient.java

took branch from #183 and rebased for current master and upgraded to latest orientdb 1.7.z.
tried changing to 2.0.10, but compilation failed.

rebased PR183: "Upgraded OrientDB"

---

core/src/main/java/com/yahoo/ycsb/measurements/Measurements.java
core/src/main/java/com/yahoo/ycsb/measurements/OneMeasurement.java
core/src/main/java/com/yahoo/ycsb/measurements/OneMeasurementHdrHistogram.java
core/src/main/java/com/yahoo/ycsb/measurements/OneMeasurementHistogram.java
core/src/main/java/com/yahoo/ycsb/measurements/OneMeasurementTimeSeries.java
core/src/main/java/com/yahoo/ycsb/measurements/TwoInOneMeasurement.java
core/src/main/java/com/yahoo/ycsb/measurements/exporter/JSONArrayMeasurementsExporter.java

and refactor *measurement* files

Fix HashMap (gh-353) bug

---

pom.xml

Update the version of the MongoDB driver to 3.0.3. Fixes #344.

[mongodb] Update the MongoDB driver version to 3.0.3.

---

hbase10/pom.xml
hbase10/src/main/java/com/yahoo/ycsb/db/HBaseClient10.java
hbase10/src/test/java/com/yahoo/ycsb/db/HBaseClient10Test.java
hbase10/src/test/resources/log4j.properties

Uses a mini-cluster to test the HBase binding.

[hbase10] Add integration tests for HBase 1.0 client

---

core/src/main/java/com/yahoo/ycsb/measurements/OneMeasurementHdrHistogram.java

Fix 90th percentile reported as 95th

---

README.md

[docs] Update README for 0.4.0 release.

---

.gitignore

[git] added standard intellij omissions to .gitignore

---

jdbc/README.md

[jdbc] added a README

---

accumulo/pom.xml
accumulo/src/main/java/com/yahoo/ycsb/db/AccumuloClient.java
accumulo/src/main/java/com/yahoo/ycsb/db/ZKProducerConsumer.java
accumulo/src/main/java/com/yahoo/ycsb/db/package-info.java

Again, a lot of whitespace changes and the normal checkstyle type errors.
2 items of note:
* Deprecated QueueElement since it is not used.
* Moved some of the exception handling to common locations to remove empty catch blocks.

[accumulo] Checkstyle cleanup and enforcement for the Accumulo binding.

---

aerospike/pom.xml
aerospike/src/main/java/com/yahoo/ycsb/db/AerospikeClient.java
aerospike/src/main/java/com/yahoo/ycsb/db/package-info.java

* Added a package-info.java.
* Added JavaDoc for the binding's DB implementation.

[aerospike] Checkstyle updates for Aerospike.

---

cassandra2/src/test/resources/ycsb.cql
core/src/main/java/com/yahoo/ycsb/Status.java
dynamodb/README.md
hypertable/README.md
jdbc/src/main/resources/sql/README
jdbc/src/main/resources/sql/README.md

Also fix a few README formatting issues.
mvn org.apache.rat:apache-rat-plugin:0.11:check -D rat.numUnapprovedLicenses=5000

[license] Apply results of Apache Rat check

---

voldemort/pom.xml
voldemort/src/main/java/com/yahoo/ycsb/db/VoldemortClient.java
voldemort/src/main/java/com/yahoo/ycsb/db/package-info.java

[voldemort] Update binding to use the new Status class and also

---

README.md

I ran into the same issue and found that this has already been addressed in an issue.
Hopefully, this will save time and frustration for others if they see it clearly in the README upfront.

Added note about Maven 3 per issue #406.

---

README.md

Also added direct link to the latest release page for easy downloading.

Update latest version and examples to 0.5.0

---

pom.xml

[kudu] revert kudu version to 0.6.0

---

mongodb/src/test/java/com/yahoo/ycsb/db/AsyncMongoDbClientTest.java
mongodb/src/test/java/com/yahoo/ycsb/db/MongoDbClientTest.java
s3/src/main/java/com/yahoo/ycsb/db/S3Client.java
tarantool/src/main/java/com/yahoo/ycsb/db/TarantoolClient.java

This pull request is focused on resolving occurrences of Sonar rule common-java:DuplicatedBlocks - Source files should not have any duplicated blocks
https://dev.eclipse.org/sonar/coding_rules#q=common-java:DuplicatedBlocks
Kirill Vlasov

Source files should not have any duplicated blocks

---

orientdb/README.md
orientdb/src/main/java/com/yahoo/ycsb/db/OrientDBClient.java

Cleaner handling of properties.
Updated documentation of available properties.
Removed default database url.
Making progress towards #539

[orientdb] properties cleanup

---

distribution/pom.xml
nosqldb/pom.xml
nosqldb/src/main/java/com/yahoo/ycsb/db/NoSqlDbClient.java
nosqldb/src/main/java/com/yahoo/ycsb/db/package-info.java
pom.xml

I found the client driver in Maven Central so I re-added the binding to the build.

Nosqldb re-added to the build and checkstyle cleanup

---

core/src/main/java/com/yahoo/ycsb/measurements/OneMeasurementTimeSeries.java

[core] synchronizing OneMeasurementTimeSeries

---

couchbase/README.md
couchbase/pom.xml
couchbase/src/main/java/com/yahoo/ycsb/db/CouchbaseClient.java

[couchbase] implemented scan for couchbase

---

couchbase/pom.xml
couchbase/src/main/java/com/yahoo/ycsb/db/CouchbaseClient.java
couchbase/src/main/java/com/yahoo/ycsb/db/package-info.java
pom.xml

Rebase and final touches on #480

Couchbase checkstyle

---

accumulo/src/test/java/com/yahoo/ycsb/db/accumulo/AccumuloTest.java

Reverts brianfrankcooper/YCSB#626
Doesn't look like travis ran on this PR?

Revert "[accumulo] don't run Accumulo tests on windows build."

---

couchbase/README.md

bad formatting in github markdown

[couchbase] nit fix in Couchbase README

---

README.md

Updated top level README for YCSB 0.7.0 release

---

core/pom.xml
core/src/main/java/com/yahoo/ycsb/Client.java
core/src/main/resources/project.properties

Not sure if this is the best way, but it seems ok to me. Opens up any other project details that you may want to expose to the client.

[core] added real version printout

---

infinispan/pom.xml
infinispan/src/main/java/com/yahoo/ycsb/db/InfinispanClient.java
infinispan/src/main/java/com/yahoo/ycsb/db/InfinispanRemoteClient.java
infinispan/src/main/java/com/yahoo/ycsb/db/RemoteCacheManagerHolder.java
infinispan/src/main/java/com/yahoo/ycsb/db/package-info.java

Updates PR #487. Relates to #267

[infinispan] Checkstyle updates for the Infinispan binding.

---

tarantool/pom.xml
tarantool/src/main/java/com/yahoo/ycsb/db/TarantoolClient.java
tarantool/src/main/java/com/yahoo/ycsb/db/package-info.java

Updates PR #491. Relates to #267

[tarantool] Checkstyle updates for the Tarantool binding.

---

geode/pom.xml
geode/src/main/java/com/yahoo/ycsb/db/GeodeClient.java
geode/src/main/java/com/yahoo/ycsb/db/package-info.java

Updates PR #483. Relates to #267

[geode] Checkstyle updates for Apache Geode (incubating)

---

bin/ycsb
distribution/pom.xml
googlebigtable/README.md
googlebigtable/pom.xml
googlebigtable/src/main/java/com/yahoo/ycsb/db/GoogleBigtableClient.java
googlebigtable/src/main/java/com/yahoo/ycsb/db/package-info.java
pom.xml

the native Protobuf GRPC based API.

[googlebigtable] Add a Google Bigtable binding for testing load using

---

hbase10/README.md

Add documentation on how to use the hbase10 client with Google's
Bigtable.

[hbase10] Add instructions for testing against Google BigTable's HBase API.

---

hbase098/README.md

[hbase098] Add missing `writebuffersize` documentation and note to

---

googlebigtable/src/main/java/com/yahoo/ycsb/db/GoogleBigtableClient.java

who's address does not change.

[googlebigtable] Fix #697 by synchronizing on the static Config object

---

README.md

Updated top level README for YCSB 0.8.0 release

---

core/src/main/java/com/yahoo/ycsb/generator/IncrementingPrintableStringGenerator.java
core/src/test/java/com/yahoo/ycsb/generator/TestIncrementingPrintableStringGenerator.java

This will be used for #653 for databases that require keys or other values to use a limited character set. This generator will create a sequence of strings using a defined list of UTF code points from which to pull.

[core] Add an incrementing printable string generator.

---

asynchbase/pom.xml

loading outside the unit tests.

[asynchbase] Fix Netty library version issue that prevents it from

---

elasticsearch/src/main/java/com/yahoo/ycsb/db/ElasticsearchClient.java

This commit modifies the Elasticsearch client to return `Status.NOT_FOUND`
when an operation fails because the document requested does not
exist. This modifies the previous behavior which would return
`Status.ERROR` in this case.
This commit also moves the statements that would return `Status.ERROR`
into the corresponding catch blocks so that it is clear that
`Status.ERROR` is only being returned on error paths.

[elasticsearch] Return not found instead of error

---

core/pom.xml
core/src/main/java/com/yahoo/ycsb/Client.java
core/src/main/java/com/yahoo/ycsb/DBFactory.java
core/src/main/java/com/yahoo/ycsb/DBWrapper.java
core/src/main/java/com/yahoo/ycsb/TerminatorThread.java
workloads/workload_template

add basic htrace instrumentation points and configs for turning htrace on/off. defaults to off.
when merged, we should provide some sample docs on using this to solve e.g. #415 .

[core] add operation tracing via Apache HTrace.

---

couchbase2/src/main/java/com/yahoo/ycsb/db/couchbase2/Couchbase2Client.java

This PR has two changesets, where one improves the defaults to saner numbers that lead to less errors when running workloads. The other one slightly refactors & improves scan performance by avoiding unnecessary JSON marshalling.

[couchbase2] Better Defaults & Scan Refactor

---

README.md

Release 0.9.0 has been published, it's time to update the top level README.md file.

[Release] Update top level README.md file to point to 0.9.0 release.

---

kudu/src/main/java/com/yahoo/ycsb/db/KuduYCSBClient.java
pom.xml

This updates the Kudu client version to the latest published (0.9.0), and fixes a scan performance regression introduced in f66bb1484b0. cc @jdcryans @toddlipcon

[kudu] Update Kudu binding to 0.9.0

---

binding-parent/datastore-specific-descriptor/src/main/resources/assemblies/datastore-specific-assembly.xml
distribution/src/main/assembly/distribution.xml

[packaging] ensure new ycsb runner scripts are included in distribution tarballs.

---

core/src/main/java/com/yahoo/ycsb/measurements/Measurements.java

which had combined hdrhistogram with histogram like hdrhistogram+histogram.

[core] solve issue with hdrhistogram+raw 

---

couchbase2/src/main/java/com/yahoo/ycsb/db/couchbase2/Couchbase2Client.java

Hey @busbey,
these changes fix regressions introduced recently and when merged include the testing for 0.10, so they need to be backported.
one fixes a regression introdouced by select raw on key selection (not returning rows properly) and the other one fixes a regression introduced by the decode logical change.
so if you get a chance please merge and backport, then couchbase is good to go for 0.10 :)

[couchbase2] fix regressions introduced in latest changes

---

bin/ycsb
bin/ycsb.bat
bin/ycsb.sh

Point folks towards the new couchbase2 client instead of the old one, so we can eventually swap them out.
ping @daschl

[scripts, couchbase] deprecate the old 'couchbase' client in favor of 'couchbase2'.

---

geode/README.md
geode/src/main/java/com/yahoo/ycsb/db/GeodeClient.java
pom.xml

Update to Apache Geode version 1.0.0-incubating.M3
Change the data storage to use the same technique that Geode uses for JSON which yields less memory in the servers.
Update the Readme to use let the servers know that we are using PDX so queries look better.

[geode] Update to Apache Geode version 1.0.0-incubating.M3

---

binding-parent/datastore-specific-descriptor/src/main/resources/assemblies/datastore-specific-assembly.xml
distribution/src/main/assembly/distribution.xml

[packaging] Fix distribution of bindings.properties

---

pom.xml

[solr] Upgrade Solr binding to 5.5.3

---

solr/pom.xml
solr/src/main/java/com/yahoo/ycsb/db/solr/SolrClient.java
solr6/pom.xml
solr6/src/main/java/com/yahoo/ycsb/db/solr6/SolrClient.java

[solr,solr6] Add support for Kerberized Solr

---

core/src/main/java/com/yahoo/ycsb/Utils.java
core/src/main/java/com/yahoo/ycsb/generator/ScrambledZipfianGenerator.java

[core] Fix checkstyle for Utils

---

core/src/main/java/com/yahoo/ycsb/workloads/ConstantOccupancyWorkload.java
core/src/main/java/com/yahoo/ycsb/workloads/package-info.java

[core] Fix checkstyle for ConstantOccupancyWorkload

---

core/src/main/java/com/yahoo/ycsb/workloads/RestWorkload.java

[core] Fix checkstyle for RestWorkload

---

hypertable/pom.xml

[hypertable] Enforce checkstyle for Hypertable binding

---

tarantool/pom.xml

[tarantool] Enforce checkstyle for Tarantool binding

---

infinispan/pom.xml

[infinispan] Enforce checkstyle for Infinispan binding

---

geode/pom.xml

[geode] Enforce checkstyle for geode binding

---

rest/pom.xml

[rest] Disable tests for Rest binding under JDK 9

---

core/src/main/java/com/yahoo/ycsb/CommandLine.java

[core] Fix checkstyle for CommandLine

---

core/src/main/java/com/yahoo/ycsb/Client.java

[core] Fix checkstyle for Client

---

core/pom.xml

[core] Enforce checkstyle for core

---

s3/src/main/java/com/yahoo/ycsb/db/S3Client.java

Fixes #1019 
I don't have a good way to test this but it seems straight forward.

[s3] Use AWS IOUtils to read object data

---

accumulo1.6/README.md
accumulo1.7/README.md
accumulo1.8/README.md

Not sure this is really worthy of a pull-request, but the accumulo README(s) were (presumably) incorrectly referencing the aerospike-binding.

[accumulo] README was incorrectly referencing aerospike-binding

---

core/src/main/java/com/yahoo/ycsb/BasicDB.java
core/src/main/java/com/yahoo/ycsb/Client.java
core/src/main/java/com/yahoo/ycsb/GoodBadUglyDB.java
core/src/main/java/com/yahoo/ycsb/RandomByteIterator.java
core/src/main/java/com/yahoo/ycsb/Utils.java
core/src/main/java/com/yahoo/ycsb/generator/DiscreteGenerator.java
core/src/main/java/com/yahoo/ycsb/generator/ExponentialGenerator.java
core/src/main/java/com/yahoo/ycsb/generator/HistogramGenerator.java
core/src/main/java/com/yahoo/ycsb/generator/HotspotIntegerGenerator.java
core/src/main/java/com/yahoo/ycsb/generator/UniformLongGenerator.java
core/src/main/java/com/yahoo/ycsb/generator/ZipfianGenerator.java
core/src/main/java/com/yahoo/ycsb/workloads/TimeSeriesWorkload.java

Seems to be leftover from Java < 7

replace custom ThreadLocalRandom with standard one

---

bin/ycsb
bin/ycsb.bat
bin/ycsb.sh

According to http://accumulo.apache.org/release/accumulo-1.6.6/

[accumulo1.6, scripts] deprecate Accumulo 1.6 client, since Accumulo 1.6 is EOM.

---

kudu/src/main/java/com/yahoo/ycsb/db/KuduYCSBClient.java
pom.xml

A few updates for the Kudu binding to improve performance and update to the latest client library. cc @danburkert

Kudu update

---

.travis.yml
accumulo1.6/pom.xml
accumulo1.7/pom.xml
accumulo1.8/pom.xml
asynchbase/pom.xml
binding-parent/pom.xml
hbase10/pom.xml
hbase12/pom.xml
ignite/pom.xml
orientdb/pom.xml
rest/pom.xml
solr/pom.xml
solr6/pom.xml

Test against JDK 9, 10, 11

---

ignite/README.md
ignite/pom.xml
ignite/src/main/java/com/yahoo/ycsb/db/ignite/IgniteAbstractClient.java
ignite/src/main/java/com/yahoo/ycsb/db/ignite/IgniteClient.java
ignite/src/main/java/com/yahoo/ycsb/db/ignite/IgniteSqlClient.java
ignite/src/main/resources/log4j2.xml
ignite/src/test/java/com/yahoo/ycsb/db/ignite/IgniteClientCommonTest.java
ignite/src/test/java/com/yahoo/ycsb/db/ignite/IgniteClientTest.java
ignite/src/test/java/com/yahoo/ycsb/db/ignite/IgniteClientTestBase.java
ignite/src/test/java/com/yahoo/ycsb/db/ignite/IgniteSqlClientTest.java

incorporates the changes from #1189 and adds an addendum for a couple of other things from #1183

[ignite, ignite-sql] clean up for apache ignite clients Fixes for Apache Ignite client

---

ignite/README.md

[ignite] fix Ignite README.md.   

---

pom.xml

[MongoDB Java Driver Compatibility](https://docs.mongodb.com/ecosystem/drivers/driver-compatibility-reference/#java-driver-compatibility)

[mongodb] add compatibility for MongoDB 4.0

---

cloudspanner/src/main/java/com/yahoo/ycsb/db/cloudspanner/CloudSpannerClient.java
core/src/main/java/com/yahoo/ycsb/workloads/CoreWorkload.java
doc/coreproperties.html
elasticsearch/src/test/java/com/yahoo/ycsb/db/ElasticsearchClientTest.java
elasticsearch5/src/test/java/com/yahoo/ycsb/db/elasticsearch5/ElasticsearchIntegTestBase.java
kudu/src/main/java/com/yahoo/ycsb/db/KuduYCSBClient.java
rocksdb/src/test/java/com/yahoo/ycsb/db/rocksdb/RocksDBClientTest.java
solr/src/test/java/com/yahoo/ycsb/db/solr/SolrClientBaseTest.java
solr6/src/test/java/com/yahoo/ycsb/db/solr6/SolrClientBaseTest.java

[core] Handle merge conflicts for #117 and update it for newer bindings that reference field name prefix
I tested locally with the 'basic' binding and inspecting the output.

[core] Handle merge conflicts for #117 and update it for newer bindings that reference field name prefix

---

azurecosmos/src/main/java/com/yahoo/ycsb/db/AzureCosmosClient.java

Optimizing the driver and fixing the update code which was clobbering rather than updating.

Optimizing the driver and fixing update

---

ignite/README.md
pom.xml

Has been updated Apache Ignite version from 2.6.0 to 2.7.0

Apache Ignite version updated

---

README.md

[release] update README for 0.17.0 release.

---

binding-parent/pom.xml
distribution/pom.xml
pom.xml

* add project url, license, and developer section to pom
* add distribution information to pom.
* add source, javadoc, and signing plugins

[release] configuration needed for publishing to maven central.

---

ignite/README.md

Fixes file path for the configuration files of ignite.

[ignite] Fixes configuration file path in README

---

README.md
mongodb/src/main/java/site/ycsb/db/MongoDbClient.java
pom.xml

upgraded MongoDB to latest driver
allow SRV style mongodb URI
fix readme example for building just mongodb-binding

[MongoDB] latest driver, allow SRV URI format, readme fix

---

cassandra/README.md
cassandra/src/main/java/site/ycsb/db/CassandraCQLClient.java

replace consistency ONE with QUORUM

[cassandra] replace consistency ONE with QUORUM

---

pom.xml
scylla/README.md
scylla/src/main/java/site/ycsb/db/scylla/ScyllaCQLClient.java

[scylla] enable token aware LB by default
[scylla] doc: add latency correction section
[scylla] doc: dump and merge histograms
[scylla] doc: don't configure connections manually
closes https://github.com/brianfrankcooper/YCSB/issues/1491

[scylla] enable token aware LB by default, improve the docs

---

README.md

@busbey you asked for it (https://github.com/brianfrankcooper/YCSB/pull/1507#pullrequestreview-591345620), you get it ;)
This PR updates a README.md file with the information about how to work with latency percentiles and that a user shall not look up for averages.

doc: percentiles and hdr merge
